home-wifi: ENC[AES256_GCM,data:DPs1/evSzQ6Ps6Ca/Q==,iv:HHjSXdSCwZBdJoz7UVHbCo+FZPMsXTERV+iWihcbOeI=,tag:GirSkve09leqlUJZOjQgDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-30T12:17:38Z"
    mac: ENC[AES256_GCM,data:W9hKkGzQVHN3kiV9fvLpZJWYSXXMAguF20X75V4rjGxoV17gfTTVM5Ojyh6u6JgqR3avjXEgUxX9tPJkNlTvcDnkrYV3W5iTOmIrQ4q+9lAkRh548Db2gA2H6ajByntxFIkBv+xcqVRTao/jpSAzILOAdRrSerfCRQG0k7poj34=,iv:OZhVEpFyQhxHkooL6ONF4p8xfLSIMmez74iL3rV1NOU=,tag:NV6dcGwn2lKM7ofJPAhlIQ==,type:str]
    pgp:
        - created_at: "2024-08-30T12:13:48Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6smtgkkGn+yAQ/8CTi1HXmL4NVVe/vK3NyiUbQjoxqsVRo4QxZRazy3Nxvs
            UUYn5No5CMmKu6znTnfs8sm2nB05H2HPLeXp6daWbW25BluI0dkq+6ZPIPy8fona
            gLpjzJEc7ZrAvdkXPQfIXXdYLHOhl+H/0+PlxTGQIinhAqe3K/Pqrv/hl8xSkzcu
            42Msw6L/evdQP6q4bpbseqFChbmBQ/OH5Y3CPXWsBnqilZEYbmbfF70ipmJHCyNB
            gwGgIXMzqeNbR9p2wiYgu8fopydsvM6dQdlaTYnU3A7nKhR10TQunBn2lHp4a5nl
            hvZKRUG3iqK95clJj1M5hCyroBC2uO7V6tnKMkZV3LKZ9bnAk2mttT94iXHPulnH
            /cLNPw6sfnaLgKqbrX1XYQyk+4o7rLRSdV3ZMpOj/OwE1DQf+Bh67gK8FQrnzwBJ
            8SfoSCD7nLtvDaq5qj6pHgHkzj5jAMsD2sN18iMXBfU7brATC6NwJtsWmeL6LqJV
            rXEWaSUWOeWVlQ2k10O7psAWx0pnYoYi8ButClPOB+ab/9vKuKTYgo6/yM9kJ/Mi
            UFRaVMLt2fN2dmjShW7rfdieoqpB0iv80HPiuJRz7MTil5bI6daIEcCCEIT7ybxS
            d/q52tmgMINIF1rFZcOpWtQiAVvYK9O7IyB8rNLmbmCS0AxHTjgG330kEvrkrVPU
            aAEJAhD48jY3jf2YkWFWVWZkkKsSmIhWBIcik8kWBAc6eparaRZGloalWWhr6lwH
            GFmpBOv3Hbg9Ewu1Dswuh7avK/At1bUrmnuzdTFUt4sANrXR4i7JBAMSANyYxPA6
            OyFsSMq3LneN
            =ypPT
            -----END PGP MESSAGE-----
          fp: 0B10DAA7BA0236D7382287660F79C0AB03FD7A1C
    unencrypted_suffix: _unencrypted
    version: 3.9.0
