# for tig
[dracula-tig]
src.git = "https://github.com/dracula/tig"
src.branch = "master"
fetch.github = "dracula/tig"

# for bat

[dracula-sublime]
src.git = "https://github.com/dracula/sublime"
src.branch = "master"
fetch.github = "dracula/sublime"

[sublime-gleam]
src.git = "https://github.com/molnarmark/sublime-gleam"
src.branch = "main"
fetch.github = "molnarmark/sublime-gleam"

# for fish

[fish-bd]
src.git = "https://github.com/0rax/fish-bd"
src.branch = "master"
fetch.github = "0rax/fish-bd"

[fish-artisan-completion]
src.git = "https://github.com/adriaanzon/fish-artisan-completion"
src.branch = "master"
fetch.github = "adriaanzon/fish-artisan-completion"

[fish-ghq]
src.git = "https://github.com/decors/fish-ghq"
src.branch = "master"
fetch.github = "decors/fish-ghq"

[dracula-fish]
src.git = "https://github.com/dracula/fish"
src.branch = "master"
fetch.github = "dracula/fish"

[fish-done]
src.git = "https://github.com/franciscolourenco/done"
src.branch = "master"
fetch.github = "franciscolourenco/done"

[fish-autopair]
src.git = "https://github.com/jorgebucaran/autopair.fish"
src.branch = "main"
fetch.github = "jorgebucaran/autopair.fish"

[fish-nix-completions]
src.git = "https://github.com/kidonng/nix-completions.fish"
src.branch = "master"
fetch.github = "kidonng/nix-completions.fish"

[fish-nix-env]
src.git = "https://github.com/lilyball/nix-env.fish"
src.branch = "master"
fetch.github = "lilyball/nix-env.fish"

[fish-dart-completions]
src.git = "https://github.com/takeokunn/fish-dart-completions"
src.branch = "main"
fetch.github = "takeokunn/fish-dart-completions"

# for emacs

[emacs-copilot]
src.git = "https://github.com/copilot-emacs/copilot.el"
src.branch = "main"
fetch.github = "copilot-emacs/copilot.el"

[emacs-llm]
src.github_tag = "ahyatt/llm"
fetch.github = "ahyatt/llm"

[emacs-rainbow-csv]
src.git = "https://github.com/emacs-vs/rainbow-csv"
src.branch = "master"
fetch.github = "emacs-vs/rainbow-csv"

[emacs-php-doc-block]
src.git = "https://github.com/moskalyovd/emacs-php-doc-block"
src.branch = "master"
fetch.github = "moskalyovd/emacs-php-doc-block"

[emacs-fish-repl]
src.git = "https://github.com/takeokunn/fish-repl.el"
src.branch = "main"
fetch.github = "takeokunn/fish-repl.el"

[emacs-eshell-multiple]
src.git = "https://github.com/takeokunn/eshell-multiple"
src.branch = "main"
fetch.github = "takeokunn/eshell-multiple"

[emacs-bazel-mode]
src.git = "https://github.com/bazelbuild/emacs-bazel-mode"
src.branch = "master"
fetch.github = "bazelbuild/emacs-bazel-mode"

[emacs-direnv-mode]
src.github_tag = "wbolster/emacs-direnv"
fetch.github = "wbolster/emacs-direnv"

[emacs-systemd-mode]
src.git = "https://github.com/holomorph/systemd-mode"
src.branch = "master"
fetch.github = "holomorph/systemd-mode"

[emacs-web-php-blade-mode]
src.git = "https://github.com/takeokunn/web-php-blade-mode"
src.branch = "main"
fetch.github = "takeokunn/web-php-blade-mode"

[emacs-org-view-mode]
src.git = "https://github.com/amno1/org-view-mode"
src.branch = "main"
fetch.github = "amno1/org-view-mode"

[emacs-org-dashboard]
src.git = "https://github.com/bard/org-dashboard"
src.branch = "master"
fetch.github = "bard/org-dashboard"

[emacs-org-volume]
src.git = "https://github.com/akirak/org-volume"
src.branch = "master"
fetch.github = "akirak/org-volume"

[emacs-ob-phpstan]
src.git = "https://github.com/emacs-php/ob-phpstan"
src.branch = "main"
fetch.github = "emacs-php/ob-phpstan"

[emacs-ob-treesitter]
src.git = "https://github.com/takeokunn/ob-treesitter"
src.branch = "main"
fetch.github = "takeokunn/ob-treesitter"

[emacs-ob-racket]
src.git = "https://github.com/hasu/emacs-ob-racket"
src.branch = "master"
fetch.github = "hasu/emacs-ob-racket"

[emacs-ox-hatena]
src.git = "https://github.com/zonkyy/ox-hatena"
src.branch = "master"
fetch.github = "zonkyy/ox-hatena"

[emacs-flycheck-projectile]
src.git = "https://github.com/nbfalcon/flycheck-projectile"
src.branch = "master"
fetch.github = "nbfalcon/flycheck-projectile"

[emacs-consult-tramp]
src.git = "https://github.com/Ladicle/consult-tramp"
src.branch = "main"
fetch.github = "Ladicle/consult-tramp"

[emacs-explain-pause-mode]
src.git = "https://github.com/lastquestion/explain-pause-mode"
src.branch = "master"
fetch.github = "lastquestion/explain-pause-mode"

[emacs-mu4e-dashboard]
src.git = "https://github.com/rougier/mu4e-dashboard"
src.branch = "main"
fetch.github = "rougier/mu4e-dashboard"

[emacs-pinentry]
src.git = "https://github.com/ueno/pinentry-el"
src.branch = "master"
fetch.github = "ueno/pinentry-el"

[emacs-sudden-death]
src.git = "https://github.com/yewton/sudden-death.el"
src.branch = "master"
fetch.github = "yewton/sudden-death.el"

[emacs-plz-event-source]
src.git = "https://github.com/r0man/plz-event-source"
src.branch = "main"
fetch.github = "r0man/plz-event-source"

[emacs-plz-media-type]
src.git = "https://github.com/r0man/plz-media-type"
src.branch = "main"
fetch.github = "r0man/plz-media-type"

[emacs-zalgo-mode]
src.git = "https://github.com/nehrbash/zalgo-mode"
src.branch = "main"
fetch.github = "nehrbash/zalgo-mode"

[emacs-ob-fish]
src.git = "https://github.com/takeokunn/ob-fish"
src.branch = "main"
fetch.github = "takeokunn/ob-fish"

[emacs-ox-typst]
src.git = "https://github.com/jmpunkt/ox-typst"
src.branch = "main"
fetch.github = "jmpunkt/ox-typst"

[emacs-typst-mode]
src.git = "https://github.com/Ziqi-Yang/typst-mode.el"
src.branch = "main"
fetch.github = "Ziqi-Yang/typst-mode.el"

[emacs-copilot-chat]
src.github_tag = "chep/copilot-chat.el"
fetch.github = "chep/copilot-chat.el"

[emacs-eglot-booster]
src.git = "https://github.com/jdtsmith/eglot-booster"
src.branch = "main"
fetch.github = "jdtsmith/eglot-booster"

[emacs-aio]
src.github_tag = "skeeto/emacs-aio"
fetch.github = "skeeto/emacs-aio"

# for neovim

[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
src.branch = "master"
fetch.github = "vim-jp/vimdoc-ja"

[vim-skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
src.branch = "main"
fetch.github = "vim-skk/skkeleton"

[vim-skkeleton-azik]
src.git = "https://github.com/kei-s16/skkeleton-azik-kanatable"
src.branch = "main"
fetch.github = "kei-s16/skkeleton-azik-kanatable"

[vim-neco]
src.git = "https://github.com/Shougo/neco-vim"
src.branch = "master"
fetch.github = "Shougo/neco-vim"

[vim-friendly-snippets]
src.git = "https://github.com/rafamadriz/friendly-snippets"
src.branch = "main"
fetch.github = "rafamadriz/friendly-snippets"

[vim-denippet-autoimport-vscode]
src.git = "https://github.com/ryoppippi/denippet-autoimport-vscode"
src.branch = "main"
fetch.github = "ryoppippi/denippet-autoimport-vscode"

[vim-denippet]
src.git = "https://github.com/uga-rosa/denippet.vim"
src.branch = "main"
fetch.github = "uga-rosa/denippet.vim"

[vim-nerdfont]
src.git = "https://github.com/lambdalisue/vim-nerdfont"
src.branch = "master"
fetch.github = "lambdalisue/vim-nerdfont"

[vim-fern]
src.git = "https://github.com/lambdalisue/vim-fern"
src.branch = "main"
fetch.github = "lambdalisue/vim-fern"

[vim-fern-renderer-nerdfont]
src.git = "https://github.com/lambdalisue/vim-fern-renderer-nerdfont"
src.branch = "master"
fetch.github = "lambdalisue/vim-fern-renderer-nerdfont"

[vim-gin]
src.git = "https://github.com/lambdalisue/vim-gin"
src.branch = "main"
fetch.github = "lambdalisue/vim-gin"
