# for tig
[dracula-tig]
src.git = "https://github.com/dracula/tig"
src.branch = "master"
fetch.github = "dracula/tig"

# for bat

[dracula-sublime]
src.git = "https://github.com/dracula/sublime"
src.branch = "master"
fetch.github = "dracula/sublime"

[sublime-gleam]
src.git = "https://github.com/molnarmark/sublime-gleam"
src.branch = "main"
fetch.github = "molnarmark/sublime-gleam"

# for fish

[fish-bd]
src.git = "https://github.com/0rax/fish-bd"
src.branch = "master"
fetch.github = "0rax/fish-bd"

[fish-artisan-completion]
src.git = "https://github.com/adriaanzon/fish-artisan-completion"
src.branch = "master"
fetch.github = "adriaanzon/fish-artisan-completion"

[fish-ghq]
src.git = "https://github.com/decors/fish-ghq"
src.branch = "master"
fetch.github = "decors/fish-ghq"

[dracula-fish]
src.git = "https://github.com/dracula/fish"
src.branch = "master"
fetch.github = "dracula/fish"

[fish-done]
src.git = "https://github.com/franciscolourenco/done"
src.branch = "master"
fetch.github = "franciscolourenco/done"

[fish-autopair]
src.git = "https://github.com/jorgebucaran/autopair.fish"
src.branch = "main"
fetch.github = "jorgebucaran/autopair.fish"

[fish-nix-completions]
src.git = "https://github.com/kidonng/nix-completions.fish"
src.branch = "master"
fetch.github = "kidonng/nix-completions.fish"

[fish-nix-env]
src.git = "https://github.com/lilyball/nix-env.fish"
src.branch = "master"
fetch.github = "lilyball/nix-env.fish"

[fish-dart-completions]
src.git = "https://github.com/takeokunn/fish-dart-completions"
src.branch = "main"
fetch.github = "takeokunn/fish-dart-completions"

# for emacs

[emacs-copilot]
src.git = "https://github.com/copilot-emacs/copilot.el"
src.branch = "main"
fetch.github = "copilot-emacs/copilot.el"

[emacs-llm]
src.git = "https://github.com/ahyatt/llm"
src.branch = "main"
fetch.github = "ahyatt/llm"

[emacs-rainbow-csv]
src.git = "https://github.com/emacs-vs/rainbow-csv"
src.branch = "master"
fetch.github = "emacs-vs/rainbow-csv"

[emacs-php-doc-block]
src.git = "https://github.com/moskalyovd/emacs-php-doc-block"
src.branch = "master"
fetch.github = "moskalyovd/emacs-php-doc-block"

[emacs-fish-repl]
src.git = "https://github.com/takeokunn/fish-repl.el"
src.branch = "main"
fetch.github = "takeokunn/fish-repl.el"

[emacs-eshell-multiple]
src.git = "https://github.com/takeokunn/eshell-multiple"
src.branch = "main"
fetch.github = "takeokunn/eshell-multiple"

[emacs-bazel-mode]
src.git = "https://github.com/bazelbuild/emacs-bazel-mode"
src.branch = "master"
fetch.github = "bazelbuild/emacs-bazel-mode"

[emacs-direnv-mode]
src.git = "https://github.com/wbolster/emacs-direnv"
src.branch = "main"
fetch.github = "wbolster/emacs-direnv"

[emacs-systemd-mode]
src.git = "https://github.com/holomorph/systemd-mode"
src.branch = "master"
fetch.github = "holomorph/systemd-mode"

[emacs-web-php-blade-mode]
src.git = "https://github.com/takeokunn/web-php-blade-mode"
src.branch = "main"
fetch.github = "takeokunn/web-php-blade-mode"

[emacs-org-view-mode]
src.git = "https://github.com/amno1/org-view-mode"
src.branch = "main"
fetch.github = "amno1/org-view-mode"

[emacs-org-dashboard]
src.git = "https://github.com/bard/org-dashboard"
src.branch = "master"
fetch.github = "bard/org-dashboard"

[emacs-org-volume]
src.git = "https://github.com/akirak/org-volume"
src.branch = "master"
fetch.github = "akirak/org-volume"

[emacs-ob-phpstan]
src.git = "https://github.com/emacs-php/ob-phpstan"
src.branch = "main"
fetch.github = "emacs-php/ob-phpstan"

[emacs-ob-treesitter]
src.git = "https://github.com/takeokunn/ob-treesitter"
src.branch = "main"
fetch.github = "takeokunn/ob-treesitter"

[emacs-ob-racket]
src.git = "https://github.com/hasu/emacs-ob-racket"
src.branch = "master"
fetch.github = "hasu/emacs-ob-racket"

[emacs-ox-hatena]
src.git = "https://github.com/zonkyy/ox-hatena"
src.branch = "master"
fetch.github = "zonkyy/ox-hatena"

[emacs-flycheck-projectile]
src.git = "https://github.com/nbfalcon/flycheck-projectile"
src.branch = "master"
fetch.github = "nbfalcon/flycheck-projectile"

[emacs-view-lock-mode]
src.git = "https://github.com/s-fubuki/view-lock-mode"
src.branch = "main"
fetch.github = "s-fubuki/view-lock-mode"

[emacs-consult-tramp]
src.git = "https://github.com/Ladicle/consult-tramp"
src.branch = "main"
fetch.github = "Ladicle/consult-tramp"

[emacs-explain-pause-mode]
src.git = "https://github.com/lastquestion/explain-pause-mode"
src.branch = "master"
fetch.github = "lastquestion/explain-pause-mode"

[emacs-mu4e-dashboard]
src.git = "https://github.com/rougier/mu4e-dashboard"
src.branch = "main"
fetch.github = "rougier/mu4e-dashboard"

[emacs-pinentry]
src.git = "https://github.com/ueno/pinentry-el"
src.branch = "master"
fetch.github = "ueno/pinentry-el"

[emacs-sudden-death]
src.git = "https://github.com/yewton/sudden-death.el"
src.branch = "master"
fetch.github = "yewton/sudden-death.el"

[emacs-plz-event-source]
src.git = "https://github.com/r0man/plz-event-source"
src.branch = "main"
fetch.github = "r0man/plz-event-source"

[emacs-plz-media-type]
src.git = "https://github.com/r0man/plz-media-type"
src.branch = "main"
fetch.github = "r0man/plz-media-type"

[emacs-zalgo-mode]
src.git = "https://github.com/nehrbash/zalgo-mode"
src.branch = "main"
fetch.github = "nehrbash/zalgo-mode"

# for neovim

[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
src.branch = "master"
fetch.github = "vim-jp/vimdoc-ja"

[denops-helloworld]
src.git = "https://github.com/vim-denops/denops-helloworld.vim"
src.branch = "main"
fetch.github = "vim-denops/denops-helloworld.vim"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
src.branch = "main"
fetch.github = "vim-skk/skkeleton"

[vim-ddu]
src.git = "https://github.com/Shougo/ddu.vim"
src.branch = "main"
fetch.github = "Shougo/ddu.vim"

[vim-ddu-ui-ff]
src.git = "https://github.com/Shougo/ddu-ui-ff"
src.branch = "main"
fetch.github = "Shougo/ddu-ui-ff"

[vim-ddu-ui-filer]
src.git = "https://github.com/Shougo/ddu-ui-filer"
src.branch = "main"
fetch.github = "Shougo/ddu-ui-filer"

[vim-ddu-kind-file]
src.git = "https://github.com/Shougo/ddu-kind-file"
src.branch = "main"
fetch.github = "Shougo/ddu-kind-file"

[vim-ddu-kind-word]
src.git = "https://github.com/Shougo/ddu-kind-word"
src.branch = "main"
fetch.github = "Shougo/ddu-kind-word"

[vim-ddu-source-file]
src.git = "https://github.com/Shougo/ddu-source-file"
src.branch = "main"
fetch.github = "Shougo/ddu-source-file"

[vim-ddu-source-file_rec]
src.git = "https://github.com/Shougo/ddu-source-file_rec"
src.branch = "main"
fetch.github = "Shougo/ddu-source-file_rec"

[vim-ddu-source-line]
src.git = "https://github.com/Shougo/ddu-source-line"
src.branch = "main"
fetch.github = "Shougo/ddu-source-line"

[vim-ddu-filter-matcher_substring]
src.git = "https://github.com/Shougo/ddu-filter-matcher_substring"
src.branch = "main"
fetch.github = "Shougo/ddu-filter-matcher_substring"

[vim-ddu-filter-matcher_hidden]
src.git = "https://github.com/Shougo/ddu-filter-matcher_hidden"
src.branch = "main"
fetch.github = "Shougo/ddu-filter-matcher_hidden"

[vim-ddu-filter-matcher_relative]
src.git = "https://github.com/Shougo/ddu-filter-matcher_relative"
src.branch = "main"
fetch.github = "Shougo/ddu-filter-matcher_relative"

[vim-ddu-source-path_history]
src.git = "https://github.com/Shougo/ddu-source-path_history"
src.branch = "main"
fetch.github = "Shougo/ddu-source-path_history"

[vim-ddu-source-action]
src.git = "https://github.com/Shougo/ddu-source-action"
src.branch = "main"
fetch.github = "Shougo/ddu-source-action"

[vim-ddu-source-register]
src.git = "https://github.com/Shougo/ddu-source-register"
src.branch = "main"
fetch.github = "Shougo/ddu-source-register"

[vim-ddu-source-dummy]
src.git = "https://github.com/Shougo/ddu-source-dummy"
src.branch = "main"
fetch.github = "Shougo/ddu-source-dummy"

[vim-ddu-source-ghq]
src.git = "https://github.com/4513ECHO/ddu-source-ghq"
src.branch = "main"
fetch.github = "4513ECHO/ddu-source-ghq"

[vim-readme-viewer]
src.git = "https://github.com/4513ECHO/vim-readme-viewer"
src.branch = "main"
fetch.github = "4513ECHO/vim-readme-viewer"

[vim-ddu-filter-kensaku]
src.git = "https://github.com/Milly/ddu-filter-kensaku"
src.branch = "master"
fetch.github = "Milly/ddu-filter-kensaku"

[vim-ddu-filter-merge]
src.git = "https://github.com/Milly/ddu-filter-merge"
src.branch = "master"
fetch.github = "Milly/ddu-filter-merge"

[vim-ddu-filter-converter_relativepath]
src.git = "https://github.com/gamoutatsumi/ddu-filter-converter_relativepath"
src.branch = "main"
fetch.github = "gamoutatsumi/ddu-filter-converter_relativepath"

[vim-ddu-filter-fuse]
src.git = "https://github.com/kuuote/ddu-filter-fuse"
src.branch = "main"
fetch.github = "kuuote/ddu-filter-fuse"

[vim-ddu-source-git_diff]
src.git = "https://github.com/kuuote/ddu-source-git_diff"
src.branch = "main"
fetch.github = "kuuote/ddu-source-git_diff"

[vim-ddu-source-git_status]
src.git = "https://github.com/kuuote/ddu-source-git_status"
src.branch = "main"
fetch.github = "kuuote/ddu-source-git_status"

[vim-ddu-source-mr]
src.git = "https://github.com/kuuote/ddu-source-mr"
src.branch = "main"
fetch.github = "kuuote/ddu-source-mr"

[vim-ddu-filter-converter_hl_dir]
src.git = "https://github.com/kyoh86/ddu-filter-converter_hl_dir"
src.branch = "main"
fetch.github = "kyoh86/ddu-filter-converter_hl_dir"

[vim-ddu-source-git_branch]
src.git = "https://github.com/kyoh86/ddu-source-git_branch"
src.branch = "main"
fetch.github = "kyoh86/ddu-source-git_branch"

[vim-ddu-source-git_diff_tree]
src.git = "https://github.com/kyoh86/ddu-source-git_diff_tree"
src.branch = "main"
fetch.github = "kyoh86/ddu-source-git_diff_tree"

[vim-ddu-source-git_log]
src.git = "https://github.com/kyoh86/ddu-source-git_log"
src.branch = "main"
fetch.github = "kyoh86/ddu-source-git_log"

[vim-ddu-source-file_external]
src.git = "https://github.com/matsui54/ddu-source-file_external"
src.branch = "main"
fetch.github = "matsui54/ddu-source-file_external"

[vim-ddu-source-help]
src.git = "https://github.com/matsui54/ddu-source-help"
src.branch = "main"
fetch.github = "matsui54/ddu-source-help"

[vim-ddu-source-highlight]
src.git = "https://github.com/matsui54/ddu-source-highlight"
src.branch = "main"
fetch.github = "matsui54/ddu-source-highlight"

[vim-ddu-column-icon_filename]
src.git = "https://github.com/ryota2357/ddu-column-icon_filename"
src.branch = "main"
fetch.github = "ryota2357/ddu-column-icon_filename"

[vim-ddu-source-buffer]
src.git = "https://github.com/shun/ddu-source-buffer"
src.branch = "main"
fetch.github = "shun/ddu-source-buffer"

[vim-ddu-source-rg]
src.git = "https://github.com/shun/ddu-source-rg"
src.branch = "main"
fetch.github = "shun/ddu-source-rg"

[vim-ddu-filter-converter_devicon]
src.git = "https://github.com/uga-rosa/ddu-filter-converter_devicon"
src.branch = "main"
fetch.github = "uga-rosa/ddu-filter-converter_devicon"

[vim-ddu-source-lsp]
src.git = "https://github.com/uga-rosa/ddu-source-lsp"
src.branch = "main"
fetch.github = "uga-rosa/ddu-source-lsp"

[vim-ddu-gh_project]
src.git = "https://github.com/yasunori0418/ddu-gh_project"
src.branch = "main"
fetch.github = "yasunori0418/ddu-gh_project"

[vim-ddu-source-nvim-notify]
src.git = "https://github.com/yuki-yano/ddu-source-nvim-notify"
src.branch = "main"
fetch.github = "yuki-yano/ddu-source-nvim-notify"

[vim-ddc-source-file]
src.git = "https://github.com/LumaKernel/ddc-source-file"
src.branch = "main"
fetch.github = "LumaKernel/ddc-source-file"

[vim-ddc-converter_remove_overlap]
src.git = "https://github.com/Shougo/ddc-converter_remove_overlap"
src.branch = "main"
fetch.github = "Shougo/ddc-converter_remove_overlap"

[vim-ddc-matcher_head]
src.git = "https://github.com/Shougo/ddc-matcher_head"
src.branch = "main"
fetch.github = "Shougo/ddc-matcher_head"

[vim-ddc-matcher_length]
src.git = "https://github.com/Shougo/ddc-matcher_length"
src.branch = "main"
fetch.github = "Shougo/ddc-matcher_length"

[vim-ddc-sorter_rank]
src.git = "https://github.com/Shougo/ddc-sorter_rank"
src.branch = "main"
fetch.github = "Shougo/ddc-sorter_rank"

[vim-ddc-source-around]
src.git = "https://github.com/Shougo/ddc-source-around"
src.branch = "main"
fetch.github = "Shougo/ddc-source-around"

[vim-ddc-source-cmdline]
src.git = "https://github.com/Shougo/ddc-source-cmdline"
src.branch = "main"
fetch.github = "Shougo/ddc-source-cmdline"

[vim-ddc-source-cmdline-history]
src.git = "https://github.com/Shougo/ddc-source-cmdline-history"
src.branch = "main"
fetch.github = "Shougo/ddc-source-cmdline-history"

[vim-ddc-source-codeium]
src.git = "https://github.com/Shougo/ddc-source-codeium"
src.branch = "main"
fetch.github = "Shougo/ddc-source-codeium"

[vim-ddc-source-input]
src.git = "https://github.com/Shougo/ddc-source-input"
src.branch = "main"
fetch.github = "Shougo/ddc-source-input"

[vim-ddc-source-line]
src.git = "https://github.com/Shougo/ddc-source-line"
src.branch = "main"
fetch.github = "Shougo/ddc-source-line"

[vim-ddc-source-lsp]
src.git = "https://github.com/Shougo/ddc-source-lsp"
src.branch = "main"
fetch.github = "Shougo/ddc-source-lsp"

[vim-ddc-source-rg]
src.git = "https://github.com/Shougo/ddc-source-rg"
src.branch = "main"
fetch.github = "Shougo/ddc-source-rg"

[vim-ddc-source-shell-native]
src.git = "https://github.com/Shougo/ddc-source-shell-native"
src.branch = "main"
fetch.github = "Shougo/ddc-source-shell-native"

[vim-ddc-ui-pum]
src.git = "https://github.com/Shougo/ddc-ui-pum"
src.branch = "main"
fetch.github = "Shougo/ddc-ui-pum"

[vim-ddc]
src.git = "https://github.com/Shougo/ddc.vim"
src.branch = "main"
fetch.github = "Shougo/ddc.vim"

[vim-neco]
src.git = "https://github.com/Shougo/neco-vim"
src.branch = "master"
fetch.github = "Shougo/neco-vim"

[vim-pum]
src.git = "https://github.com/Shougo/pum.vim"
src.branch = "main"
fetch.github = "Shougo/pum.vim"

[vim-ddc-shell-history]
src.git = "https://github.com/delphinus/ddc-shell-history"
src.branch = "main"
fetch.github = "delphinus/ddc-shell-history"

[vim-ddc-buffer]
src.git = "https://github.com/matsui54/ddc-buffer"
src.branch = "main"
fetch.github = "matsui54/ddc-buffer"

[vim-friendly-snippets]
src.git = "https://github.com/rafamadriz/friendly-snippets"
src.branch = "main"
fetch.github = "rafamadriz/friendly-snippets"

[vim-denippet-autoimport-vscode]
src.git = "https://github.com/ryoppippi/denippet-autoimport-vscode"
src.branch = "main"
fetch.github = "ryoppippi/denippet-autoimport-vscode"

[vim-ddc-fuzzy]
src.git = "https://github.com/tani/ddc-fuzzy"
src.branch = "main"
fetch.github = "tani/ddc-fuzzy"

[vim-ddc-source-lsp-setup]
src.git = "https://github.com/uga-rosa/ddc-source-lsp-setup"
src.branch = "main"
fetch.github = "uga-rosa/ddc-source-lsp-setup"

[vim-ddc-source-nvim-lua]
src.git = "https://github.com/uga-rosa/ddc-source-nvim-lua"
src.branch = "main"
fetch.github = "uga-rosa/ddc-source-nvim-lua"

[vim-denippet]
src.git = "https://github.com/uga-rosa/denippet.vim"
src.branch = "main"
fetch.github = "uga-rosa/denippet.vim"

[vim-fern]
src.git = "https://github.com/lambdalisue/vim-fern"
src.branch = "main"
fetch.github = "lambdalisue/vim-fern"

[vim-gin]
src.git = "https://github.com/lambdalisue/vim-gin"
src.branch = "main"
fetch.github = "lambdalisue/vim-gin"
