# for bat

[dracula-sublime]
src.git = "https://github.com/dracula/sublime"
src.branch = "master"
fetch.github = "dracula/sublime"

[sublime-gleam]
src.git = "https://github.com/molnarmark/sublime-gleam"
src.branch = "main"
fetch.github = "molnarmark/sublime-gleam"

# for fish

[fish-bd]
src.git = "https://github.com/0rax/fish-bd"
src.branch = "master"
fetch.github = "0rax/fish-bd"

[fish-artisan-completion]
src.git = "https://github.com/adriaanzon/fish-artisan-completion"
src.branch = "master"
fetch.github = "adriaanzon/fish-artisan-completion"

[fish-ghq]
src.git = "https://github.com/decors/fish-ghq"
src.branch = "master"
fetch.github = "decors/fish-ghq"

[dracula-fish]
src.git = "https://github.com/dracula/fish"
src.branch = "master"
fetch.github = "dracula/fish"

[fish-done]
src.git = "https://github.com/franciscolourenco/done"
src.branch = "master"
fetch.github = "franciscolourenco/done"

[fish-autopair]
src.git = "https://github.com/jorgebucaran/autopair.fish"
src.branch = "main"
fetch.github = "jorgebucaran/autopair.fish"

[fish-nix-completions]
src.git = "https://github.com/kidonng/nix-completions.fish"
src.branch = "master"
fetch.github = "kidonng/nix-completions.fish"

[fish-nix-env]
src.git = "https://github.com/lilyball/nix-env.fish"
src.branch = "master"
fetch.github = "lilyball/nix-env.fish"

[fish-dart-completions]
src.git = "https://github.com/takeokunn/fish-dart-completions"
src.branch = "main"
fetch.github = "takeokunn/fish-dart-completions"

# for neovim

[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
src.branch = "master"
fetch.github = "vim-jp/vimdoc-ja"

[denops-helloworld]
src.git = "https://github.com/vim-denops/denops-helloworld.vim"
src.branch = "main"
fetch.github = "vim-denops/denops-helloworld.vim"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
src.branch = "main"
fetch.github = "vim-skk/skkeleton"

# for emacs

[emacs-copilot]
src.git = "https://github.com/copilot-emacs/copilot.el"
src.branch = "main"
fetch.github = "copilot-emacs/copilot.el"

[emacs-llm]
src.git = "https://github.com/ahyatt/llm"
src.branch = "main"
fetch.github = "ahyatt/llm"

[emacs-rainbow-csv]
src.git = "https://github.com/emacs-vs/rainbow-csv"
src.branch = "master"
fetch.github = "emacs-vs/rainbow-csv"

[emacs-php-doc-block]
src.git = "https://github.com/moskalyovd/emacs-php-doc-block"
src.branch = "master"
fetch.github = "moskalyovd/emacs-php-doc-block"

[emacs-fish-repl]
src.git = "https://github.com/takeokunn/fish-repl.el"
src.branch = "main"
fetch.github = "takeokunn/fish-repl.el"

[emacs-eshell-fringe-status]
src.git = "https://github.com/ryuslash/eshell-fringe-status"
src.branch = "master"
fetch.github = "ryuslash/eshell-fringe-status"

[emacs-eshell-multiple]
src.git = "https://github.com/takeokunn/eshell-multiple"
src.branch = "main"
fetch.github = "takeokunn/eshell-multiple"

[emacs-eshell-syntax-highlighting]
src.git = "https://github.com/akreisher/eshell-syntax-highlighting"
src.branch = "master"
fetch.github = "akreisher/eshell-syntax-highlighting"

[emacs-bazel-mode]
src.git = "https://github.com/bazelbuild/emacs-bazel-mode"
src.branch = "master"
fetch.github = "bazelbuild/emacs-bazel-mode"

[emacs-direnv-mode]
src.git = "https://github.com/wbolster/emacs-direnv"
src.branch = "main"
fetch.github = "wbolster/emacs-direnv"

[emacs-systemd-mode]
src.git = "https://github.com/holomorph/systemd-mode"
src.branch = "master"
fetch.github = "holomorph/systemd-mode"

[emacs-web-php-blade-mode]
src.git = "https://github.com/takeokunn/web-php-blade-mode"
src.branch = "main"
fetch.github = "takeokunn/web-php-blade-mode"

[emacs-org-view-mode]
src.git = "https://github.com/amno1/org-view-mode"
src.branch = "main"
fetch.github = "amno1/org-view-mode"

[emacs-org-dashboard]
src.git = "https://github.com/bard/org-dashboard"
src.branch = "master"
fetch.github = "bard/org-dashboard"

[emacs-org-volume]
src.git = "https://github.com/akirak/org-volume"
src.branch = "master"
fetch.github = "akirak/org-volume"

[emacs-ob-phpstan]
src.git = "https://github.com/emacs-php/ob-phpstan"
src.branch = "main"
fetch.github = "emacs-php/ob-phpstan"

[emacs-ob-treesitter]
src.git = "https://github.com/takeokunn/ob-treesitter"
src.branch = "main"
fetch.github = "takeokunn/ob-treesitter"

[emacs-ox-hatena]
src.git = "https://github.com/zonkyy/ox-hatena"
src.branch = "master"
fetch.github = "zonkyy/ox-hatena"

[emacs-flycheck-projectile]
src.git = "https://github.com/nbfalcon/flycheck-projectile"
src.branch = "master"
fetch.github = "nbfalcon/flycheck-projectile"

[emacs-view-lock-mode]
src.git = "https://github.com/s-fubuki/view-lock-mode"
src.branch = "main"
fetch.github = "s-fubuki/view-lock-mode"

[emacs-consult-tramp]
src.git = "https://github.com/Ladicle/consult-tramp"
src.branch = "main"
fetch.github = "Ladicle/consult-tramp"

[emacs-explain-pause-mode]
src.git = "https://github.com/lastquestion/explain-pause-mode"
src.branch = "master"
fetch.github = "lastquestion/explain-pause-mode"

[emacs-mu4e-dashboard]
src.git = "https://github.com/rougier/mu4e-dashboard"
src.branch = "main"
fetch.github = "rougier/mu4e-dashboard"

[emacs-pinentry]
src.git = "https://github.com/ueno/pinentry-el"
src.branch = "master"
fetch.github = "ueno/pinentry-el"

[emacs-sudden-death]
src.git = "https://github.com/yewton/sudden-death.el"
src.branch = "master"
fetch.github = "yewton/sudden-death.el"
