# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  denops-helloworld = {
    pname = "denops-helloworld";
    version = "f975281571191cfd4e3f9e5ba77103932f7dd6e5";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops-helloworld.vim";
      rev = "f975281571191cfd4e3f9e5ba77103932f7dd6e5";
      fetchSubmodules = false;
      sha256 = "sha256-w+UIj+IM/Me4Jp81bujlQLpOGUssWEqmZ3xUmWn5+mE=";
    };
    date = "2024-07-27";
  };
  dracula-fish = {
    pname = "dracula-fish";
    version = "269cd7d76d5104fdc2721db7b8848f6224bdf554";
    src = fetchFromGitHub {
      owner = "dracula";
      repo = "fish";
      rev = "269cd7d76d5104fdc2721db7b8848f6224bdf554";
      fetchSubmodules = false;
      sha256 = "sha256-Hyq4EfSmWmxwCYhp3O8agr7VWFAflcUe8BUKh50fNfY=";
    };
    date = "2023-06-23";
  };
  dracula-sublime = {
    pname = "dracula-sublime";
    version = "456d3289827964a6cb503a3b0a6448f4326f291b";
    src = fetchFromGitHub {
      owner = "dracula";
      repo = "sublime";
      rev = "456d3289827964a6cb503a3b0a6448f4326f291b";
      fetchSubmodules = false;
      sha256 = "sha256-8mCovVSrBjtFi5q+XQdqAaqOt3Q+Fo29eIDwECOViro=";
    };
    date = "2023-08-30";
  };
  emacs-bazel-mode = {
    pname = "emacs-bazel-mode";
    version = "769b30dc18282564d614d7044195b5a0c1a0a5f3";
    src = fetchFromGitHub {
      owner = "bazelbuild";
      repo = "emacs-bazel-mode";
      rev = "769b30dc18282564d614d7044195b5a0c1a0a5f3";
      fetchSubmodules = false;
      sha256 = "sha256-riB6U1gTuYdStwzejvlsSneMYYFSDvdUFNdaFx3l8BA=";
    };
    date = "2023-09-19";
  };
  emacs-consult-tramp = {
    pname = "emacs-consult-tramp";
    version = "befa62baca768caa457b167e773b91f1bc7d661f";
    src = fetchFromGitHub {
      owner = "Ladicle";
      repo = "consult-tramp";
      rev = "befa62baca768caa457b167e773b91f1bc7d661f";
      fetchSubmodules = false;
      sha256 = "sha256-Ddeat4FfQS+5BvAP41xNsNw3bzTJv41xuaIA5a44Kvc=";
    };
    date = "2022-03-17";
  };
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "535ef61e82f09d744cd5b097b1fc99f08cce175c";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "535ef61e82f09d744cd5b097b1fc99f08cce175c";
      fetchSubmodules = false;
      sha256 = "sha256-/ZDnEZWUFcKnUtFrd/4C7LX16GAdUQncU8ZnYzntKS0=";
    };
    date = "2024-08-16";
  };
  emacs-direnv-mode = {
    pname = "emacs-direnv-mode";
    version = "c0bf3b81c7a97e2a0d06d05495e86848254fcc1f";
    src = fetchFromGitHub {
      owner = "wbolster";
      repo = "emacs-direnv";
      rev = "c0bf3b81c7a97e2a0d06d05495e86848254fcc1f";
      fetchSubmodules = false;
      sha256 = "sha256-g500rooMfkVX22u/HNELT+rKv0+q51Xg4k4R48fPyKw=";
    };
    date = "2024-03-14";
  };
  emacs-eshell-fringe-status = {
    pname = "emacs-eshell-fringe-status";
    version = "adc6997c68e39c0d52a2af1b2fd5cf2057783797";
    src = fetchFromGitHub {
      owner = "ryuslash";
      repo = "eshell-fringe-status";
      rev = "adc6997c68e39c0d52a2af1b2fd5cf2057783797";
      fetchSubmodules = false;
      sha256 = "sha256-QHJxU+fX6sr0duNEdObRY7cqnfqdGX3mLJQ0KTcjlrM=";
    };
    date = "2017-01-18";
  };
  emacs-eshell-multiple = {
    pname = "emacs-eshell-multiple";
    version = "342c36ef9c71df8738f4435fd4381f506631e7aa";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "eshell-multiple";
      rev = "342c36ef9c71df8738f4435fd4381f506631e7aa";
      fetchSubmodules = false;
      sha256 = "sha256-+4x8Xkaqj44rcvrqv/3M8p+b842c6uLNBGPMaDtQUbs=";
    };
    date = "2022-08-17";
  };
  emacs-eshell-syntax-highlighting = {
    pname = "emacs-eshell-syntax-highlighting";
    version = "26f49633308ea876b5850256e07622de34ad0bdd";
    src = fetchFromGitHub {
      owner = "akreisher";
      repo = "eshell-syntax-highlighting";
      rev = "26f49633308ea876b5850256e07622de34ad0bdd";
      fetchSubmodules = false;
      sha256 = "sha256-MPypD9p1gUEFGQmq06vCcmuQa9E2dVsVDba6n0fHVNw=";
    };
    date = "2024-06-30";
  };
  emacs-explain-pause-mode = {
    pname = "emacs-explain-pause-mode";
    version = "2356c8c3639cbeeb9751744dbe737267849b4b51";
    src = fetchFromGitHub {
      owner = "lastquestion";
      repo = "explain-pause-mode";
      rev = "2356c8c3639cbeeb9751744dbe737267849b4b51";
      fetchSubmodules = false;
      sha256 = "sha256-++znrjiDSx+cy4okFBBXUBkRFdtnE2x+trkmqjB3Njs=";
    };
    date = "2020-07-27";
  };
  emacs-fish-repl = {
    pname = "emacs-fish-repl";
    version = "5dd66957e494ea201de6e2b0c934dbac6f12743a";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "fish-repl.el";
      rev = "5dd66957e494ea201de6e2b0c934dbac6f12743a";
      fetchSubmodules = false;
      sha256 = "sha256-6clzUsB7dllXKe5CeT0kwZl5Cjs9KKhPFaDa9B0aUHE=";
    };
    date = "2021-09-24";
  };
  emacs-flycheck-projectile = {
    pname = "emacs-flycheck-projectile";
    version = "ce6e9e8793a55dace13d5fa13badab2dca3b5ddb";
    src = fetchFromGitHub {
      owner = "nbfalcon";
      repo = "flycheck-projectile";
      rev = "ce6e9e8793a55dace13d5fa13badab2dca3b5ddb";
      fetchSubmodules = false;
      sha256 = "sha256-p3/y9iTfgYKJyRNXF2cB7Jam36QWIq4/ZUB+G+YRHjQ=";
    };
    date = "2020-10-31";
  };
  emacs-llm = {
    pname = "emacs-llm";
    version = "152a6ed44ae43641e35a0d2ce2cf9f9d35f23999";
    src = fetchFromGitHub {
      owner = "ahyatt";
      repo = "llm";
      rev = "152a6ed44ae43641e35a0d2ce2cf9f9d35f23999";
      fetchSubmodules = false;
      sha256 = "sha256-jYt0VlZsjXYjmNvvSnHDnjFNfTraXZHfn9MJkq+Py18=";
    };
    date = "2024-09-06";
  };
  emacs-mu4e-dashboard = {
    pname = "emacs-mu4e-dashboard";
    version = "c9c09b7ed6433070de148b656ac273b7fb7cec07";
    src = fetchFromGitHub {
      owner = "rougier";
      repo = "mu4e-dashboard";
      rev = "c9c09b7ed6433070de148b656ac273b7fb7cec07";
      fetchSubmodules = false;
      sha256 = "sha256-bCelxaT+qaR2W80Cr591A4cRycIFJmXjeY8/aqIpl5g=";
    };
    date = "2024-01-22";
  };
  emacs-ob-phpstan = {
    pname = "emacs-ob-phpstan";
    version = "c77355e70703affffb166b7100b9e9f3efb21c6e";
    src = fetchFromGitHub {
      owner = "emacs-php";
      repo = "ob-phpstan";
      rev = "c77355e70703affffb166b7100b9e9f3efb21c6e";
      fetchSubmodules = false;
      sha256 = "sha256-UTWlpszxXC1sue6E72bIeL+1NKzJ+VC1WQBXOZD0mwI=";
    };
    date = "2024-03-27";
  };
  emacs-ob-treesitter = {
    pname = "emacs-ob-treesitter";
    version = "c3fac35f95dcaffdb90836c606d119717c43238d";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "ob-treesitter";
      rev = "c3fac35f95dcaffdb90836c606d119717c43238d";
      fetchSubmodules = false;
      sha256 = "sha256-3lroCj3FhRS1wgb/UVHYO4CjgP1rsicqB/rARvzsfoc=";
    };
    date = "2024-01-06";
  };
  emacs-org-dashboard = {
    pname = "emacs-org-dashboard";
    version = "02c0699771d199075a286e4502340ca6e7c9e831";
    src = fetchFromGitHub {
      owner = "bard";
      repo = "org-dashboard";
      rev = "02c0699771d199075a286e4502340ca6e7c9e831";
      fetchSubmodules = false;
      sha256 = "sha256-OWwRHMFJvxIKwu+6wdsd+b2zRTX3Q0nbEQi7sl8fIn4=";
    };
    date = "2017-12-23";
  };
  emacs-org-view-mode = {
    pname = "emacs-org-view-mode";
    version = "16d7c87a1bef54abd892f0fda2a541043c42e097";
    src = fetchFromGitHub {
      owner = "amno1";
      repo = "org-view-mode";
      rev = "16d7c87a1bef54abd892f0fda2a541043c42e097";
      fetchSubmodules = false;
      sha256 = "sha256-bLRUHFzVA6+04iY1tnmFQzBRgW6P09+gK9it8D8QrVA=";
    };
    date = "2024-02-18";
  };
  emacs-org-volume = {
    pname = "emacs-org-volume";
    version = "caa30d5b958c9f37854d7ab35c99445c00bc7d1e";
    src = fetchFromGitHub {
      owner = "akirak";
      repo = "org-volume";
      rev = "caa30d5b958c9f37854d7ab35c99445c00bc7d1e";
      fetchSubmodules = false;
      sha256 = "sha256-J1DdP10uc6KeWl+ZhsEBifEJ99lDyKlmcuInHa5p3/M=";
    };
    date = "2024-07-23";
  };
  emacs-ox-hatena = {
    pname = "emacs-ox-hatena";
    version = "24777234566f5472b0e8b3c5faeb2e045fd91e12";
    src = fetchFromGitHub {
      owner = "zonkyy";
      repo = "ox-hatena";
      rev = "24777234566f5472b0e8b3c5faeb2e045fd91e12";
      fetchSubmodules = false;
      sha256 = "sha256-gQ6oU2t/xlyTK4FRInqeHd9AH+vRpCBM/aMbpn1tHTU=";
    };
    date = "2013-08-23";
  };
  emacs-php-doc-block = {
    pname = "emacs-php-doc-block";
    version = "bdf1ddba2cadd52ee7dd5691baefc6306ea62c81";
    src = fetchFromGitHub {
      owner = "moskalyovd";
      repo = "emacs-php-doc-block";
      rev = "bdf1ddba2cadd52ee7dd5691baefc6306ea62c81";
      fetchSubmodules = false;
      sha256 = "sha256-pmCOsKcKcFNZP/ipj5bj9IAK+Ulthso+HQKpzakRCzA=";
    };
    date = "2020-03-23";
  };
  emacs-pinentry = {
    pname = "emacs-pinentry";
    version = "a6441224da04656370e993e2616185cc31afaff9";
    src = fetchFromGitHub {
      owner = "ueno";
      repo = "pinentry-el";
      rev = "a6441224da04656370e993e2616185cc31afaff9";
      fetchSubmodules = false;
      sha256 = "sha256-xgzdwLEsjjkyPB6z1WM/N+rZNbndKXMPNUZ7Uaa8zT8=";
    };
    date = "2023-11-26";
  };
  emacs-rainbow-csv = {
    pname = "emacs-rainbow-csv";
    version = "aa09e2cc79d32f890177c6d0b0376c4aa2708d3e";
    src = fetchFromGitHub {
      owner = "emacs-vs";
      repo = "rainbow-csv";
      rev = "aa09e2cc79d32f890177c6d0b0376c4aa2708d3e";
      fetchSubmodules = false;
      sha256 = "sha256-5EoBFKgUDLyC9oZDP7vY3Ldk6An39Qo4ngkIHgrB8dU=";
    };
    date = "2024-07-21";
  };
  emacs-sudden-death = {
    pname = "emacs-sudden-death";
    version = "791a63d3f4df192e71f4232a9a4c5588f4b43dfb";
    src = fetchFromGitHub {
      owner = "yewton";
      repo = "sudden-death.el";
      rev = "791a63d3f4df192e71f4232a9a4c5588f4b43dfb";
      fetchSubmodules = false;
      sha256 = "sha256-+h6nWW9upcwWfIvYaF4It38+ouhqeBttm1dVbxpvanw=";
    };
    date = "2018-02-17";
  };
  emacs-systemd-mode = {
    pname = "emacs-systemd-mode";
    version = "8742607120fbc440821acbc351fda1e8e68a8806";
    src = fetchFromGitHub {
      owner = "holomorph";
      repo = "systemd-mode";
      rev = "8742607120fbc440821acbc351fda1e8e68a8806";
      fetchSubmodules = false;
      sha256 = "sha256-oj/E+b3oS/2QNNxTYDZ5Zwq/OHKI2FgN/eRV5EAexrE=";
    };
    date = "2023-01-31";
  };
  emacs-view-lock-mode = {
    pname = "emacs-view-lock-mode";
    version = "508b1a4b6d5e040455535331244104f5122e340b";
    src = fetchFromGitHub {
      owner = "s-fubuki";
      repo = "view-lock-mode";
      rev = "508b1a4b6d5e040455535331244104f5122e340b";
      fetchSubmodules = false;
      sha256 = "sha256-WUhQO/4O0NBpUfNofGUsS7Rfbel8iEGk+qCyOs9o0Ik=";
    };
    date = "2024-07-06";
  };
  emacs-web-php-blade-mode = {
    pname = "emacs-web-php-blade-mode";
    version = "a4463d2732caa8c3650826ee4fc79f3fd29c9e56";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "web-php-blade-mode";
      rev = "a4463d2732caa8c3650826ee4fc79f3fd29c9e56";
      fetchSubmodules = false;
      sha256 = "sha256-hZKMck0xJWTub81yCupCie+Z8FFFFP26IRm7uN/mbTI=";
    };
    date = "2022-06-22";
  };
  fish-artisan-completion = {
    pname = "fish-artisan-completion";
    version = "8e8d726b3862fcb972abb652fb8c1a9fb9207a64";
    src = fetchFromGitHub {
      owner = "adriaanzon";
      repo = "fish-artisan-completion";
      rev = "8e8d726b3862fcb972abb652fb8c1a9fb9207a64";
      fetchSubmodules = false;
      sha256 = "sha256-+LKQVuWORJcyuL/YZ3B86hpbV4rbSkj41Y9qgwXZXu4=";
    };
    date = "2021-11-16";
  };
  fish-autopair = {
    pname = "fish-autopair";
    version = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
      fetchSubmodules = false;
      sha256 = "sha256-qt3t1iKRRNuiLWiVoiAYOu+9E7jsyECyIqZJ/oRIT1A=";
    };
    date = "2022-07-04";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
    src = fetchFromGitHub {
      owner = "0rax";
      repo = "fish-bd";
      rev = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
      fetchSubmodules = false;
      sha256 = "sha256-GeWjoakXa0t2TsMC/wpLEmsSVGhHFhBVK3v9eyQdzv0=";
    };
    date = "2022-03-04";
  };
  fish-dart-completions = {
    pname = "fish-dart-completions";
    version = "f52734d3bbb79f362aa6541b490f74df49f124ff";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "fish-dart-completions";
      rev = "f52734d3bbb79f362aa6541b490f74df49f124ff";
      fetchSubmodules = false;
      sha256 = "sha256-CSvMkY5ObtAowr+PsPtJxsWaTZENgP5HrUU/PUoMtOw=";
    };
    date = "2021-09-25";
  };
  fish-done = {
    pname = "fish-done";
    version = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
    src = fetchFromGitHub {
      owner = "franciscolourenco";
      repo = "done";
      rev = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
      fetchSubmodules = false;
      sha256 = "sha256-DMIRKRAVOn7YEnuAtz4hIxrU93ULxNoQhW6juxCoh4o=";
    };
    date = "2024-04-11";
  };
  fish-ghq = {
    pname = "fish-ghq";
    version = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-ghq";
      rev = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
      fetchSubmodules = false;
      sha256 = "sha256-6b1zmjtemNLNPx4qsXtm27AbtjwIZWkzJAo21/aVZzM=";
    };
    date = "2021-07-16";
  };
  fish-nix-completions = {
    pname = "fish-nix-completions";
    version = "cd8a43bed96e0acc02228bc77502be8ba5fa0548";
    src = fetchFromGitHub {
      owner = "kidonng";
      repo = "nix-completions.fish";
      rev = "cd8a43bed96e0acc02228bc77502be8ba5fa0548";
      fetchSubmodules = false;
      sha256 = "sha256-spnLmde41qQt8uJZFwiH0igFuVqZ6SvkwdA9Kbe2yz8=";
    };
    date = "2022-08-18";
  };
  fish-nix-env = {
    pname = "fish-nix-env";
    version = "7b65bd228429e852c8fdfa07601159130a818cfa";
    src = fetchFromGitHub {
      owner = "lilyball";
      repo = "nix-env.fish";
      rev = "7b65bd228429e852c8fdfa07601159130a818cfa";
      fetchSubmodules = false;
      sha256 = "sha256-RG/0rfhgq6aEKNZ0XwIqOaZ6K5S4+/Y5EEMnIdtfPhk=";
    };
    date = "2021-11-29";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "882ec0c10856aadd0c2bf843b9b04cf16272a19b";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "882ec0c10856aadd0c2bf843b9b04cf16272a19b";
      fetchSubmodules = false;
      sha256 = "sha256-b3tDU4iz0tV3mebSPlmvXDSrvw8hdR5w0EPyDXjaiqA=";
    };
    date = "2024-09-03";
  };
  sublime-gleam = {
    pname = "sublime-gleam";
    version = "ff9638511e05b0aca236d63071c621977cffce38";
    src = fetchFromGitHub {
      owner = "molnarmark";
      repo = "sublime-gleam";
      rev = "ff9638511e05b0aca236d63071c621977cffce38";
      fetchSubmodules = false;
      sha256 = "sha256-94moZz9r5cMVPWTyzGlbpu9p2p/5Js7/KV6V4Etqvbo=";
    };
    date = "2020-10-25";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "1fa7e5b4f332aec82d70db4524f80be3be45e992";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "1fa7e5b4f332aec82d70db4524f80be3be45e992";
      fetchSubmodules = false;
      sha256 = "sha256-aUZp/FjZSUeHa6L1cJdOC4pzvrNV3AiqXumLVZLEoig=";
    };
    date = "2024-09-03";
  };
}
