# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dracula-sublime = {
    pname = "dracula-sublime";
    version = "456d3289827964a6cb503a3b0a6448f4326f291b";
    src = fetchFromGitHub {
      owner = "dracula";
      repo = "sublime";
      rev = "456d3289827964a6cb503a3b0a6448f4326f291b";
      fetchSubmodules = false;
      sha256 = "sha256-8mCovVSrBjtFi5q+XQdqAaqOt3Q+Fo29eIDwECOViro=";
    };
    date = "2023-08-30";
  };
  sublime-gleam = {
    pname = "sublime-gleam";
    version = "ff9638511e05b0aca236d63071c621977cffce38";
    src = fetchFromGitHub {
      owner = "molnarmark";
      repo = "sublime-gleam";
      rev = "ff9638511e05b0aca236d63071c621977cffce38";
      fetchSubmodules = false;
      sha256 = "sha256-94moZz9r5cMVPWTyzGlbpu9p2p/5Js7/KV6V4Etqvbo=";
    };
    date = "2020-10-25";
  };
}
