# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  denops-helloworld = {
    pname = "denops-helloworld";
    version = "f975281571191cfd4e3f9e5ba77103932f7dd6e5";
    src = fetchFromGitHub {
      owner = "vim-denops";
      repo = "denops-helloworld.vim";
      rev = "f975281571191cfd4e3f9e5ba77103932f7dd6e5";
      fetchSubmodules = false;
      sha256 = "sha256-w+UIj+IM/Me4Jp81bujlQLpOGUssWEqmZ3xUmWn5+mE=";
    };
    date = "2024-07-27";
  };
  dracula-fish = {
    pname = "dracula-fish";
    version = "269cd7d76d5104fdc2721db7b8848f6224bdf554";
    src = fetchFromGitHub {
      owner = "dracula";
      repo = "fish";
      rev = "269cd7d76d5104fdc2721db7b8848f6224bdf554";
      fetchSubmodules = false;
      sha256 = "sha256-Hyq4EfSmWmxwCYhp3O8agr7VWFAflcUe8BUKh50fNfY=";
    };
    date = "2023-06-23";
  };
  dracula-sublime = {
    pname = "dracula-sublime";
    version = "456d3289827964a6cb503a3b0a6448f4326f291b";
    src = fetchFromGitHub {
      owner = "dracula";
      repo = "sublime";
      rev = "456d3289827964a6cb503a3b0a6448f4326f291b";
      fetchSubmodules = false;
      sha256 = "sha256-8mCovVSrBjtFi5q+XQdqAaqOt3Q+Fo29eIDwECOViro=";
    };
    date = "2023-08-30";
  };
  dracula-tig = {
    pname = "dracula-tig";
    version = "e8a3387d8353e90cca41f5d89c3e1f74f1f7c8c6";
    src = fetchFromGitHub {
      owner = "dracula";
      repo = "tig";
      rev = "e8a3387d8353e90cca41f5d89c3e1f74f1f7c8c6";
      fetchSubmodules = false;
      sha256 = "sha256-PnBuQJWCqARvjZg/Mfi7imcTa+I4VYvnYSt+GGMzxCQ=";
    };
    date = "2022-03-20";
  };
  emacs-bazel-mode = {
    pname = "emacs-bazel-mode";
    version = "769b30dc18282564d614d7044195b5a0c1a0a5f3";
    src = fetchFromGitHub {
      owner = "bazelbuild";
      repo = "emacs-bazel-mode";
      rev = "769b30dc18282564d614d7044195b5a0c1a0a5f3";
      fetchSubmodules = false;
      sha256 = "sha256-riB6U1gTuYdStwzejvlsSneMYYFSDvdUFNdaFx3l8BA=";
    };
    date = "2023-09-19";
  };
  emacs-consult-tramp = {
    pname = "emacs-consult-tramp";
    version = "befa62baca768caa457b167e773b91f1bc7d661f";
    src = fetchFromGitHub {
      owner = "Ladicle";
      repo = "consult-tramp";
      rev = "befa62baca768caa457b167e773b91f1bc7d661f";
      fetchSubmodules = false;
      sha256 = "sha256-Ddeat4FfQS+5BvAP41xNsNw3bzTJv41xuaIA5a44Kvc=";
    };
    date = "2022-03-17";
  };
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "b5878d6a8c741138b5efbf4fe1c594f3fd69dbdd";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "b5878d6a8c741138b5efbf4fe1c594f3fd69dbdd";
      fetchSubmodules = false;
      sha256 = "sha256-02ywlMPku1FIritZjjtxbQW6MmPvSwmRCrudYsUb8bU=";
    };
    date = "2024-09-25";
  };
  emacs-direnv-mode = {
    pname = "emacs-direnv-mode";
    version = "c0bf3b81c7a97e2a0d06d05495e86848254fcc1f";
    src = fetchFromGitHub {
      owner = "wbolster";
      repo = "emacs-direnv";
      rev = "c0bf3b81c7a97e2a0d06d05495e86848254fcc1f";
      fetchSubmodules = false;
      sha256 = "sha256-g500rooMfkVX22u/HNELT+rKv0+q51Xg4k4R48fPyKw=";
    };
    date = "2024-03-14";
  };
  emacs-eshell-fringe-status = {
    pname = "emacs-eshell-fringe-status";
    version = "adc6997c68e39c0d52a2af1b2fd5cf2057783797";
    src = fetchFromGitHub {
      owner = "ryuslash";
      repo = "eshell-fringe-status";
      rev = "adc6997c68e39c0d52a2af1b2fd5cf2057783797";
      fetchSubmodules = false;
      sha256 = "sha256-QHJxU+fX6sr0duNEdObRY7cqnfqdGX3mLJQ0KTcjlrM=";
    };
    date = "2017-01-18";
  };
  emacs-eshell-multiple = {
    pname = "emacs-eshell-multiple";
    version = "342c36ef9c71df8738f4435fd4381f506631e7aa";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "eshell-multiple";
      rev = "342c36ef9c71df8738f4435fd4381f506631e7aa";
      fetchSubmodules = false;
      sha256 = "sha256-+4x8Xkaqj44rcvrqv/3M8p+b842c6uLNBGPMaDtQUbs=";
    };
    date = "2022-08-17";
  };
  emacs-eshell-syntax-highlighting = {
    pname = "emacs-eshell-syntax-highlighting";
    version = "26f49633308ea876b5850256e07622de34ad0bdd";
    src = fetchFromGitHub {
      owner = "akreisher";
      repo = "eshell-syntax-highlighting";
      rev = "26f49633308ea876b5850256e07622de34ad0bdd";
      fetchSubmodules = false;
      sha256 = "sha256-MPypD9p1gUEFGQmq06vCcmuQa9E2dVsVDba6n0fHVNw=";
    };
    date = "2024-06-30";
  };
  emacs-explain-pause-mode = {
    pname = "emacs-explain-pause-mode";
    version = "2356c8c3639cbeeb9751744dbe737267849b4b51";
    src = fetchFromGitHub {
      owner = "lastquestion";
      repo = "explain-pause-mode";
      rev = "2356c8c3639cbeeb9751744dbe737267849b4b51";
      fetchSubmodules = false;
      sha256 = "sha256-++znrjiDSx+cy4okFBBXUBkRFdtnE2x+trkmqjB3Njs=";
    };
    date = "2020-07-27";
  };
  emacs-fish-repl = {
    pname = "emacs-fish-repl";
    version = "5dd66957e494ea201de6e2b0c934dbac6f12743a";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "fish-repl.el";
      rev = "5dd66957e494ea201de6e2b0c934dbac6f12743a";
      fetchSubmodules = false;
      sha256 = "sha256-6clzUsB7dllXKe5CeT0kwZl5Cjs9KKhPFaDa9B0aUHE=";
    };
    date = "2021-09-24";
  };
  emacs-flycheck-projectile = {
    pname = "emacs-flycheck-projectile";
    version = "ce6e9e8793a55dace13d5fa13badab2dca3b5ddb";
    src = fetchFromGitHub {
      owner = "nbfalcon";
      repo = "flycheck-projectile";
      rev = "ce6e9e8793a55dace13d5fa13badab2dca3b5ddb";
      fetchSubmodules = false;
      sha256 = "sha256-p3/y9iTfgYKJyRNXF2cB7Jam36QWIq4/ZUB+G+YRHjQ=";
    };
    date = "2020-10-31";
  };
  emacs-llm = {
    pname = "emacs-llm";
    version = "c81b44943b2bfeac5114566ab5ad66640bad1e3e";
    src = fetchFromGitHub {
      owner = "ahyatt";
      repo = "llm";
      rev = "c81b44943b2bfeac5114566ab5ad66640bad1e3e";
      fetchSubmodules = false;
      sha256 = "sha256-oJI4cm6suy7RIVBWv5oCl9A8Al/XkmY9RVm1G+0fczE=";
    };
    date = "2024-10-03";
  };
  emacs-mu4e-dashboard = {
    pname = "emacs-mu4e-dashboard";
    version = "c9c09b7ed6433070de148b656ac273b7fb7cec07";
    src = fetchFromGitHub {
      owner = "rougier";
      repo = "mu4e-dashboard";
      rev = "c9c09b7ed6433070de148b656ac273b7fb7cec07";
      fetchSubmodules = false;
      sha256 = "sha256-bCelxaT+qaR2W80Cr591A4cRycIFJmXjeY8/aqIpl5g=";
    };
    date = "2024-01-22";
  };
  emacs-ob-phpstan = {
    pname = "emacs-ob-phpstan";
    version = "c77355e70703affffb166b7100b9e9f3efb21c6e";
    src = fetchFromGitHub {
      owner = "emacs-php";
      repo = "ob-phpstan";
      rev = "c77355e70703affffb166b7100b9e9f3efb21c6e";
      fetchSubmodules = false;
      sha256 = "sha256-UTWlpszxXC1sue6E72bIeL+1NKzJ+VC1WQBXOZD0mwI=";
    };
    date = "2024-03-27";
  };
  emacs-ob-treesitter = {
    pname = "emacs-ob-treesitter";
    version = "c3fac35f95dcaffdb90836c606d119717c43238d";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "ob-treesitter";
      rev = "c3fac35f95dcaffdb90836c606d119717c43238d";
      fetchSubmodules = false;
      sha256 = "sha256-3lroCj3FhRS1wgb/UVHYO4CjgP1rsicqB/rARvzsfoc=";
    };
    date = "2024-01-06";
  };
  emacs-org-dashboard = {
    pname = "emacs-org-dashboard";
    version = "02c0699771d199075a286e4502340ca6e7c9e831";
    src = fetchFromGitHub {
      owner = "bard";
      repo = "org-dashboard";
      rev = "02c0699771d199075a286e4502340ca6e7c9e831";
      fetchSubmodules = false;
      sha256 = "sha256-OWwRHMFJvxIKwu+6wdsd+b2zRTX3Q0nbEQi7sl8fIn4=";
    };
    date = "2017-12-23";
  };
  emacs-org-view-mode = {
    pname = "emacs-org-view-mode";
    version = "16d7c87a1bef54abd892f0fda2a541043c42e097";
    src = fetchFromGitHub {
      owner = "amno1";
      repo = "org-view-mode";
      rev = "16d7c87a1bef54abd892f0fda2a541043c42e097";
      fetchSubmodules = false;
      sha256 = "sha256-bLRUHFzVA6+04iY1tnmFQzBRgW6P09+gK9it8D8QrVA=";
    };
    date = "2024-02-18";
  };
  emacs-org-volume = {
    pname = "emacs-org-volume";
    version = "caa30d5b958c9f37854d7ab35c99445c00bc7d1e";
    src = fetchFromGitHub {
      owner = "akirak";
      repo = "org-volume";
      rev = "caa30d5b958c9f37854d7ab35c99445c00bc7d1e";
      fetchSubmodules = false;
      sha256 = "sha256-J1DdP10uc6KeWl+ZhsEBifEJ99lDyKlmcuInHa5p3/M=";
    };
    date = "2024-07-23";
  };
  emacs-ox-hatena = {
    pname = "emacs-ox-hatena";
    version = "24777234566f5472b0e8b3c5faeb2e045fd91e12";
    src = fetchFromGitHub {
      owner = "zonkyy";
      repo = "ox-hatena";
      rev = "24777234566f5472b0e8b3c5faeb2e045fd91e12";
      fetchSubmodules = false;
      sha256 = "sha256-gQ6oU2t/xlyTK4FRInqeHd9AH+vRpCBM/aMbpn1tHTU=";
    };
    date = "2013-08-23";
  };
  emacs-php-doc-block = {
    pname = "emacs-php-doc-block";
    version = "bdf1ddba2cadd52ee7dd5691baefc6306ea62c81";
    src = fetchFromGitHub {
      owner = "moskalyovd";
      repo = "emacs-php-doc-block";
      rev = "bdf1ddba2cadd52ee7dd5691baefc6306ea62c81";
      fetchSubmodules = false;
      sha256 = "sha256-pmCOsKcKcFNZP/ipj5bj9IAK+Ulthso+HQKpzakRCzA=";
    };
    date = "2020-03-23";
  };
  emacs-pinentry = {
    pname = "emacs-pinentry";
    version = "a6441224da04656370e993e2616185cc31afaff9";
    src = fetchFromGitHub {
      owner = "ueno";
      repo = "pinentry-el";
      rev = "a6441224da04656370e993e2616185cc31afaff9";
      fetchSubmodules = false;
      sha256 = "sha256-xgzdwLEsjjkyPB6z1WM/N+rZNbndKXMPNUZ7Uaa8zT8=";
    };
    date = "2023-11-26";
  };
  emacs-plz-event-source = {
    pname = "emacs-plz-event-source";
    version = "1d584eb8d015faa839141ac68e934dde89a6e2ab";
    src = fetchFromGitHub {
      owner = "r0man";
      repo = "plz-event-source";
      rev = "1d584eb8d015faa839141ac68e934dde89a6e2ab";
      fetchSubmodules = false;
      sha256 = "sha256-V64y+9AwsbmMVfJux8WIDwP1vYuQpl5d4UBrGg4mDjo=";
    };
    date = "2024-09-24";
  };
  emacs-plz-media-type = {
    pname = "emacs-plz-media-type";
    version = "ce83948804b543cb1e22d80cc88f4bee7a23780d";
    src = fetchFromGitHub {
      owner = "r0man";
      repo = "plz-media-type";
      rev = "ce83948804b543cb1e22d80cc88f4bee7a23780d";
      fetchSubmodules = false;
      sha256 = "sha256-ueX/L/5xHPjV6rO4uQc4/ZZvmk235y9Zc3rkfAfUo/0=";
    };
    date = "2024-09-24";
  };
  emacs-rainbow-csv = {
    pname = "emacs-rainbow-csv";
    version = "aa09e2cc79d32f890177c6d0b0376c4aa2708d3e";
    src = fetchFromGitHub {
      owner = "emacs-vs";
      repo = "rainbow-csv";
      rev = "aa09e2cc79d32f890177c6d0b0376c4aa2708d3e";
      fetchSubmodules = false;
      sha256 = "sha256-5EoBFKgUDLyC9oZDP7vY3Ldk6An39Qo4ngkIHgrB8dU=";
    };
    date = "2024-07-21";
  };
  emacs-sudden-death = {
    pname = "emacs-sudden-death";
    version = "791a63d3f4df192e71f4232a9a4c5588f4b43dfb";
    src = fetchFromGitHub {
      owner = "yewton";
      repo = "sudden-death.el";
      rev = "791a63d3f4df192e71f4232a9a4c5588f4b43dfb";
      fetchSubmodules = false;
      sha256 = "sha256-+h6nWW9upcwWfIvYaF4It38+ouhqeBttm1dVbxpvanw=";
    };
    date = "2018-02-17";
  };
  emacs-systemd-mode = {
    pname = "emacs-systemd-mode";
    version = "8742607120fbc440821acbc351fda1e8e68a8806";
    src = fetchFromGitHub {
      owner = "holomorph";
      repo = "systemd-mode";
      rev = "8742607120fbc440821acbc351fda1e8e68a8806";
      fetchSubmodules = false;
      sha256 = "sha256-oj/E+b3oS/2QNNxTYDZ5Zwq/OHKI2FgN/eRV5EAexrE=";
    };
    date = "2023-01-31";
  };
  emacs-view-lock-mode = {
    pname = "emacs-view-lock-mode";
    version = "508b1a4b6d5e040455535331244104f5122e340b";
    src = fetchFromGitHub {
      owner = "s-fubuki";
      repo = "view-lock-mode";
      rev = "508b1a4b6d5e040455535331244104f5122e340b";
      fetchSubmodules = false;
      sha256 = "sha256-WUhQO/4O0NBpUfNofGUsS7Rfbel8iEGk+qCyOs9o0Ik=";
    };
    date = "2024-07-06";
  };
  emacs-web-php-blade-mode = {
    pname = "emacs-web-php-blade-mode";
    version = "a4463d2732caa8c3650826ee4fc79f3fd29c9e56";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "web-php-blade-mode";
      rev = "a4463d2732caa8c3650826ee4fc79f3fd29c9e56";
      fetchSubmodules = false;
      sha256 = "sha256-hZKMck0xJWTub81yCupCie+Z8FFFFP26IRm7uN/mbTI=";
    };
    date = "2022-06-22";
  };
  fish-artisan-completion = {
    pname = "fish-artisan-completion";
    version = "8e8d726b3862fcb972abb652fb8c1a9fb9207a64";
    src = fetchFromGitHub {
      owner = "adriaanzon";
      repo = "fish-artisan-completion";
      rev = "8e8d726b3862fcb972abb652fb8c1a9fb9207a64";
      fetchSubmodules = false;
      sha256 = "sha256-+LKQVuWORJcyuL/YZ3B86hpbV4rbSkj41Y9qgwXZXu4=";
    };
    date = "2021-11-16";
  };
  fish-autopair = {
    pname = "fish-autopair";
    version = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
    src = fetchFromGitHub {
      owner = "jorgebucaran";
      repo = "autopair.fish";
      rev = "4d1752ff5b39819ab58d7337c69220342e9de0e2";
      fetchSubmodules = false;
      sha256 = "sha256-qt3t1iKRRNuiLWiVoiAYOu+9E7jsyECyIqZJ/oRIT1A=";
    };
    date = "2022-07-04";
  };
  fish-bd = {
    pname = "fish-bd";
    version = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
    src = fetchFromGitHub {
      owner = "0rax";
      repo = "fish-bd";
      rev = "ab686e028bfe95fa561a4f4e57840e36902d4d7d";
      fetchSubmodules = false;
      sha256 = "sha256-GeWjoakXa0t2TsMC/wpLEmsSVGhHFhBVK3v9eyQdzv0=";
    };
    date = "2022-03-04";
  };
  fish-dart-completions = {
    pname = "fish-dart-completions";
    version = "f52734d3bbb79f362aa6541b490f74df49f124ff";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "fish-dart-completions";
      rev = "f52734d3bbb79f362aa6541b490f74df49f124ff";
      fetchSubmodules = false;
      sha256 = "sha256-CSvMkY5ObtAowr+PsPtJxsWaTZENgP5HrUU/PUoMtOw=";
    };
    date = "2021-09-25";
  };
  fish-done = {
    pname = "fish-done";
    version = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
    src = fetchFromGitHub {
      owner = "franciscolourenco";
      repo = "done";
      rev = "eb32ade85c0f2c68cbfcff3036756bbf27a4f366";
      fetchSubmodules = false;
      sha256 = "sha256-DMIRKRAVOn7YEnuAtz4hIxrU93ULxNoQhW6juxCoh4o=";
    };
    date = "2024-04-11";
  };
  fish-ghq = {
    pname = "fish-ghq";
    version = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
    src = fetchFromGitHub {
      owner = "decors";
      repo = "fish-ghq";
      rev = "cafaaabe63c124bf0714f89ec715cfe9ece87fa2";
      fetchSubmodules = false;
      sha256 = "sha256-6b1zmjtemNLNPx4qsXtm27AbtjwIZWkzJAo21/aVZzM=";
    };
    date = "2021-07-16";
  };
  fish-nix-completions = {
    pname = "fish-nix-completions";
    version = "cd8a43bed96e0acc02228bc77502be8ba5fa0548";
    src = fetchFromGitHub {
      owner = "kidonng";
      repo = "nix-completions.fish";
      rev = "cd8a43bed96e0acc02228bc77502be8ba5fa0548";
      fetchSubmodules = false;
      sha256 = "sha256-spnLmde41qQt8uJZFwiH0igFuVqZ6SvkwdA9Kbe2yz8=";
    };
    date = "2022-08-18";
  };
  fish-nix-env = {
    pname = "fish-nix-env";
    version = "7b65bd228429e852c8fdfa07601159130a818cfa";
    src = fetchFromGitHub {
      owner = "lilyball";
      repo = "nix-env.fish";
      rev = "7b65bd228429e852c8fdfa07601159130a818cfa";
      fetchSubmodules = false;
      sha256 = "sha256-RG/0rfhgq6aEKNZ0XwIqOaZ6K5S4+/Y5EEMnIdtfPhk=";
    };
    date = "2021-11-29";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "438737ec49bcf1303521bdcccb5e06ced7b60c5e";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "438737ec49bcf1303521bdcccb5e06ced7b60c5e";
      fetchSubmodules = false;
      sha256 = "sha256-beQDAlgM9E3Xy+xQMAIfqrc7/j5ahboHi2Wa8T8zQFU=";
    };
    date = "2024-09-28";
  };
  sublime-gleam = {
    pname = "sublime-gleam";
    version = "ff9638511e05b0aca236d63071c621977cffce38";
    src = fetchFromGitHub {
      owner = "molnarmark";
      repo = "sublime-gleam";
      rev = "ff9638511e05b0aca236d63071c621977cffce38";
      fetchSubmodules = false;
      sha256 = "sha256-94moZz9r5cMVPWTyzGlbpu9p2p/5Js7/KV6V4Etqvbo=";
    };
    date = "2020-10-25";
  };
  vim-ddc = {
    pname = "vim-ddc";
    version = "dd845f05d6be94214988afeeb59407f7f2e95945";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc.vim";
      rev = "dd845f05d6be94214988afeeb59407f7f2e95945";
      fetchSubmodules = false;
      sha256 = "sha256-E30vne60qzgOqzxfx1vWiv4HttxqxkFPpxvBAHIF35Y=";
    };
    date = "2024-10-07";
  };
  vim-ddc-buffer = {
    pname = "vim-ddc-buffer";
    version = "f332e16ed82ec31c4a5afe3da5117e0b5e0c6902";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "ddc-buffer";
      rev = "f332e16ed82ec31c4a5afe3da5117e0b5e0c6902";
      fetchSubmodules = false;
      sha256 = "sha256-Dgohfr2aJrkVUn/Y7fWSZwJqpD9VCzgP6sqcfxjh2pY=";
    };
    date = "2024-09-25";
  };
  vim-ddc-converter_remove_overlap = {
    pname = "vim-ddc-converter_remove_overlap";
    version = "dc31980cfe7635a0b15c2bae8e30cca4bbaf975e";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-converter_remove_overlap";
      rev = "dc31980cfe7635a0b15c2bae8e30cca4bbaf975e";
      fetchSubmodules = false;
      sha256 = "sha256-k2/bqMl9yAbrMZhf7uFoB9GXVUS00xnJuH45RoFxuBM=";
    };
    date = "2024-09-03";
  };
  vim-ddc-fuzzy = {
    pname = "vim-ddc-fuzzy";
    version = "ecc164ef958c087aec048915609c222d09ea3b2a";
    src = fetchFromGitHub {
      owner = "tani";
      repo = "ddc-fuzzy";
      rev = "ecc164ef958c087aec048915609c222d09ea3b2a";
      fetchSubmodules = false;
      sha256 = "sha256-WK8cdSa+fNKvO2VuTp6uxhpyNmg31JigjVcq2bLdRFo=";
    };
    date = "2024-10-12";
  };
  vim-ddc-matcher_head = {
    pname = "vim-ddc-matcher_head";
    version = "2be49f0c547fc224f70bd4a0b354b1c1dd9c9eac";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-matcher_head";
      rev = "2be49f0c547fc224f70bd4a0b354b1c1dd9c9eac";
      fetchSubmodules = false;
      sha256 = "sha256-cCAHhP6Z54r9Ryir8k8zrGPbTS1VdL3jSuIpmsemL1I=";
    };
    date = "2024-09-03";
  };
  vim-ddc-matcher_length = {
    pname = "vim-ddc-matcher_length";
    version = "05c252e62541158173757212419ab3de0f798d53";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-matcher_length";
      rev = "05c252e62541158173757212419ab3de0f798d53";
      fetchSubmodules = false;
      sha256 = "sha256-G571CoVlmbN0OEfJPrfg6jtVvm2jMFtx6wyarif+HeA=";
    };
    date = "2024-09-03";
  };
  vim-ddc-shell-history = {
    pname = "vim-ddc-shell-history";
    version = "b3aab22c09b892fee75fdf27a1bc0f9ab35fd262";
    src = fetchFromGitHub {
      owner = "delphinus";
      repo = "ddc-shell-history";
      rev = "b3aab22c09b892fee75fdf27a1bc0f9ab35fd262";
      fetchSubmodules = false;
      sha256 = "sha256-2b9sT7GbckTYu1QzYlI8UT5PKlq//SkeJPLRCCgvKDM=";
    };
    date = "2021-12-31";
  };
  vim-ddc-sorter_rank = {
    pname = "vim-ddc-sorter_rank";
    version = "98d1beaa3a94c7a1198c1d6b0440bd9bde7be212";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-sorter_rank";
      rev = "98d1beaa3a94c7a1198c1d6b0440bd9bde7be212";
      fetchSubmodules = false;
      sha256 = "sha256-Ppc00e61YYo+5Wl0YoR5drUt+1cVFNNleojz7eJcw6M=";
    };
    date = "2024-09-24";
  };
  vim-ddc-source-around = {
    pname = "vim-ddc-source-around";
    version = "b52e19f8d93d9b868842e58b211cebd5f7fe60b6";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-around";
      rev = "b52e19f8d93d9b868842e58b211cebd5f7fe60b6";
      fetchSubmodules = false;
      sha256 = "sha256-eEAPGoy4gpXiCeRlTUFaWDQVkDXROCj7jFyCsEIrUdM=";
    };
    date = "2024-09-03";
  };
  vim-ddc-source-cmdline = {
    pname = "vim-ddc-source-cmdline";
    version = "4003bc995e0c34a859a5abbfe1f78e43674822e4";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-cmdline";
      rev = "4003bc995e0c34a859a5abbfe1f78e43674822e4";
      fetchSubmodules = false;
      sha256 = "sha256-R/VTdI8p7bvcFdEPrkA/k+zjH6lVS6vB9cAIp1AB0AU=";
    };
    date = "2024-09-03";
  };
  vim-ddc-source-cmdline-history = {
    pname = "vim-ddc-source-cmdline-history";
    version = "d367d85f3ca453d77999e37029c9770e0b70e979";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-cmdline-history";
      rev = "d367d85f3ca453d77999e37029c9770e0b70e979";
      fetchSubmodules = false;
      sha256 = "sha256-Mhfhk6knvbXEJccNMzp8FIvBUZ4+vD912uZPsXgvgrI=";
    };
    date = "2024-09-03";
  };
  vim-ddc-source-codeium = {
    pname = "vim-ddc-source-codeium";
    version = "f9eca2071a330c3e8c62ae243e5e30fd711dfede";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-codeium";
      rev = "f9eca2071a330c3e8c62ae243e5e30fd711dfede";
      fetchSubmodules = false;
      sha256 = "sha256-UJt3lXGGe9gstIakOI+mfDEoALdLUBWiRYmUePtPPp4=";
    };
    date = "2024-09-24";
  };
  vim-ddc-source-file = {
    pname = "vim-ddc-source-file";
    version = "34b362d45957183b4ec99d618a19a5f5f517c365";
    src = fetchFromGitHub {
      owner = "LumaKernel";
      repo = "ddc-source-file";
      rev = "34b362d45957183b4ec99d618a19a5f5f517c365";
      fetchSubmodules = false;
      sha256 = "sha256-SC7+7dx7kyat3J8XEa+tUxlh4lwtrOyd0iE21EcyExw=";
    };
    date = "2024-09-24";
  };
  vim-ddc-source-input = {
    pname = "vim-ddc-source-input";
    version = "d8d97a1f8f6657a992dd5d21dfe851a188e7177d";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-input";
      rev = "d8d97a1f8f6657a992dd5d21dfe851a188e7177d";
      fetchSubmodules = false;
      sha256 = "sha256-EHoKfU0WegUFEcwBtaYa3qwv8z45JYapabKDGnOIm9I=";
    };
    date = "2024-09-03";
  };
  vim-ddc-source-line = {
    pname = "vim-ddc-source-line";
    version = "6d846d6d82ec3420eb7e01013c2821eafcc9bed1";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-line";
      rev = "6d846d6d82ec3420eb7e01013c2821eafcc9bed1";
      fetchSubmodules = false;
      sha256 = "sha256-VRxI7hiVd2k4mf8S96dRKFIzDGa1uPIeXN45ClWREjc=";
    };
    date = "2024-09-03";
  };
  vim-ddc-source-lsp = {
    pname = "vim-ddc-source-lsp";
    version = "23b69013f2948c80b3938165a0cb414f58e26ada";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-lsp";
      rev = "23b69013f2948c80b3938165a0cb414f58e26ada";
      fetchSubmodules = false;
      sha256 = "sha256-B8KnrDKcW8oSmlVELs1YZkGMwlWmc9ZXgOoQs0scrkA=";
    };
    date = "2024-09-15";
  };
  vim-ddc-source-lsp-setup = {
    pname = "vim-ddc-source-lsp-setup";
    version = "a8a06af203d402e0874060bcd8a0b89b32a52224";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "ddc-source-lsp-setup";
      rev = "a8a06af203d402e0874060bcd8a0b89b32a52224";
      fetchSubmodules = false;
      sha256 = "sha256-bSTA1QQPdtUxuTA73eaHtVwWFRTP/rANtidAWuWmSPc=";
    };
    date = "2023-12-08";
  };
  vim-ddc-source-nvim-lua = {
    pname = "vim-ddc-source-nvim-lua";
    version = "2b0d0f47efa14d7e7ac2c473861b095dcf99f020";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "ddc-source-nvim-lua";
      rev = "2b0d0f47efa14d7e7ac2c473861b095dcf99f020";
      fetchSubmodules = false;
      sha256 = "sha256-PrGSp7DRic7G/PPJ9IqPwvOTrfccXTLlfYmyQjomSgY=";
    };
    date = "2024-01-22";
  };
  vim-ddc-source-rg = {
    pname = "vim-ddc-source-rg";
    version = "5959f0ed4d9b8d322913ebb11197c943a466bebb";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-rg";
      rev = "5959f0ed4d9b8d322913ebb11197c943a466bebb";
      fetchSubmodules = false;
      sha256 = "sha256-ReU7ZMS4OgC/4XwavnK4ylToKJH4ys6dQNrs65KA1Dg=";
    };
    date = "2024-09-03";
  };
  vim-ddc-source-shell-native = {
    pname = "vim-ddc-source-shell-native";
    version = "ed04337908702e543aa9d95eb4de28b3a17ca529";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-source-shell-native";
      rev = "ed04337908702e543aa9d95eb4de28b3a17ca529";
      fetchSubmodules = false;
      sha256 = "sha256-3AQcfWtfIQ3G9hXeTtSdd9rQlu3JCA0hZ0Glvd4aC8M=";
    };
    date = "2024-09-03";
  };
  vim-ddc-ui-pum = {
    pname = "vim-ddc-ui-pum";
    version = "7e568274b3c22ca8d1742ddec43ea3a63d6ab7e9";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddc-ui-pum";
      rev = "7e568274b3c22ca8d1742ddec43ea3a63d6ab7e9";
      fetchSubmodules = false;
      sha256 = "sha256-UgrNYkW3a3jASzJz2x/wZaxXBEjzjsYo/dUo6O8QOME=";
    };
    date = "2024-09-03";
  };
  vim-ddu = {
    pname = "vim-ddu";
    version = "53ba00ff2aa9a06c74680e2e520364afe071d799";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu.vim";
      rev = "53ba00ff2aa9a06c74680e2e520364afe071d799";
      fetchSubmodules = false;
      sha256 = "sha256-yvM4BaXzRFicniDjeVRJZ9Dbn0atJ6kL20+whMS9YoU=";
    };
    date = "2024-10-07";
  };
  vim-ddu-column-icon_filename = {
    pname = "vim-ddu-column-icon_filename";
    version = "8c5e17e7eef61146f6ec51980b2afbae0c60116c";
    src = fetchFromGitHub {
      owner = "ryota2357";
      repo = "ddu-column-icon_filename";
      rev = "8c5e17e7eef61146f6ec51980b2afbae0c60116c";
      fetchSubmodules = false;
      sha256 = "sha256-TsETMGbRjZx7eZLnnl3JzAXRlTaPRHLWQ/zRRfn2BOY=";
    };
    date = "2024-04-28";
  };
  vim-ddu-filter-converter_devicon = {
    pname = "vim-ddu-filter-converter_devicon";
    version = "8bbf0a0457beb8defdd41abe0d6ea2fe877fa96c";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "ddu-filter-converter_devicon";
      rev = "8bbf0a0457beb8defdd41abe0d6ea2fe877fa96c";
      fetchSubmodules = false;
      sha256 = "sha256-peOm7vNQNqs/hgSOAjfgpIgQHG1E/fMnG6KHzz1DwXQ=";
    };
    date = "2023-09-01";
  };
  vim-ddu-filter-converter_hl_dir = {
    pname = "vim-ddu-filter-converter_hl_dir";
    version = "1253fd3bdf12fd049c52ebf4da3f751e915fdc7c";
    src = fetchFromGitHub {
      owner = "kyoh86";
      repo = "ddu-filter-converter_hl_dir";
      rev = "1253fd3bdf12fd049c52ebf4da3f751e915fdc7c";
      fetchSubmodules = false;
      sha256 = "sha256-4FGUN0zdFS094DQrIGqe8XCkO54OODvBJLLDYsXmWbg=";
    };
    date = "2024-09-08";
  };
  vim-ddu-filter-converter_relativepath = {
    pname = "vim-ddu-filter-converter_relativepath";
    version = "ee0e433512752a7ddcc409c5d1d050ea10a8d878";
    src = fetchFromGitHub {
      owner = "gamoutatsumi";
      repo = "ddu-filter-converter_relativepath";
      rev = "ee0e433512752a7ddcc409c5d1d050ea10a8d878";
      fetchSubmodules = false;
      sha256 = "sha256-eYRaMEt/VcUk3gnLI6iZDYCicsM0vWNqntmJyBE6ffM=";
    };
    date = "2024-08-01";
  };
  vim-ddu-filter-fuse = {
    pname = "vim-ddu-filter-fuse";
    version = "df1ed6477a3edadd19e2ecbf67d0d2990b7f727e";
    src = fetchFromGitHub {
      owner = "kuuote";
      repo = "ddu-filter-fuse";
      rev = "df1ed6477a3edadd19e2ecbf67d0d2990b7f727e";
      fetchSubmodules = false;
      sha256 = "sha256-eHVBRrczIDIGCCVTBQy24EyKTWG4X/ve9SbrZ1cYui8=";
    };
    date = "2023-08-23";
  };
  vim-ddu-filter-kensaku = {
    pname = "vim-ddu-filter-kensaku";
    version = "2d920c077fd0e1d81533c13c0f1fe32c1f9a599c";
    src = fetchFromGitHub {
      owner = "Milly";
      repo = "ddu-filter-kensaku";
      rev = "2d920c077fd0e1d81533c13c0f1fe32c1f9a599c";
      fetchSubmodules = false;
      sha256 = "sha256-AHgecmCKcfgEFnXOu2wHjGqsGVp+rpH7KRk7x5QFIoE=";
    };
    date = "2024-08-01";
  };
  vim-ddu-filter-matcher_hidden = {
    pname = "vim-ddu-filter-matcher_hidden";
    version = "61848581edfdcbb9a22fee2d45ee0f6ad5a0469a";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-filter-matcher_hidden";
      rev = "61848581edfdcbb9a22fee2d45ee0f6ad5a0469a";
      fetchSubmodules = false;
      sha256 = "sha256-hQGZEUdyvs2Mou43Avqk82nlTRAdm+zJx1c9aj2BXYo=";
    };
    date = "2024-09-03";
  };
  vim-ddu-filter-matcher_relative = {
    pname = "vim-ddu-filter-matcher_relative";
    version = "b94f477541f0e0a3f538041ac321d48ad7e486a5";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-filter-matcher_relative";
      rev = "b94f477541f0e0a3f538041ac321d48ad7e486a5";
      fetchSubmodules = false;
      sha256 = "sha256-T0Qw33r9cQnMXjQozVNaVEHsNJJGK6QmNJp+pNqufyc=";
    };
    date = "2024-09-03";
  };
  vim-ddu-filter-matcher_substring = {
    pname = "vim-ddu-filter-matcher_substring";
    version = "d6defcd1f4a87cc717a72cc620307f9b1e11290d";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-filter-matcher_substring";
      rev = "d6defcd1f4a87cc717a72cc620307f9b1e11290d";
      fetchSubmodules = false;
      sha256 = "sha256-NDN3NIzM8eD+BU+6vl4grKXV0uvpAp30ziSuobfgkDs=";
    };
    date = "2024-09-03";
  };
  vim-ddu-filter-merge = {
    pname = "vim-ddu-filter-merge";
    version = "06dec27e83ec61702737fe5d31ef001ba4502481";
    src = fetchFromGitHub {
      owner = "Milly";
      repo = "ddu-filter-merge";
      rev = "06dec27e83ec61702737fe5d31ef001ba4502481";
      fetchSubmodules = false;
      sha256 = "sha256-nGSZjcq3FJQz6TrCXGAKfPUYviBlaQED2zkEQ+1WxJY=";
    };
    date = "2024-08-02";
  };
  vim-ddu-gh_project = {
    pname = "vim-ddu-gh_project";
    version = "b4fb3eef8e1b21294d9588c27ef6a45c5f7c7298";
    src = fetchFromGitHub {
      owner = "yasunori0418";
      repo = "ddu-gh_project";
      rev = "b4fb3eef8e1b21294d9588c27ef6a45c5f7c7298";
      fetchSubmodules = false;
      sha256 = "sha256-l7q55QA8DoACkmxLaRfxvgdA5XX0NqlAi49mbDtQj/Y=";
    };
    date = "2024-07-17";
  };
  vim-ddu-kind-file = {
    pname = "vim-ddu-kind-file";
    version = "eb5efbe36e7202f0c155e99a3150c4d6e1ca7951";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-kind-file";
      rev = "eb5efbe36e7202f0c155e99a3150c4d6e1ca7951";
      fetchSubmodules = false;
      sha256 = "sha256-vX0C4O3X3IarcS8UYvnr29QRrQKMIksKXQMv4sh4dkI=";
    };
    date = "2024-09-15";
  };
  vim-ddu-kind-word = {
    pname = "vim-ddu-kind-word";
    version = "35dbe749281291e5a056a50c9bc301f6e31720f2";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-kind-word";
      rev = "35dbe749281291e5a056a50c9bc301f6e31720f2";
      fetchSubmodules = false;
      sha256 = "sha256-CLnyfIR1VPsPPN6zXqTmxl2DomyymU8G0bdQtRZ7VL0=";
    };
    date = "2024-09-01";
  };
  vim-ddu-source-action = {
    pname = "vim-ddu-source-action";
    version = "3584cec7b248615ec3afb98de64202ff7cbacdfe";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-action";
      rev = "3584cec7b248615ec3afb98de64202ff7cbacdfe";
      fetchSubmodules = false;
      sha256 = "sha256-72KKXfMHeyWqDlmvpU9UQjjwQJFZxMiQrZGpk3d4t10=";
    };
    date = "2024-09-04";
  };
  vim-ddu-source-buffer = {
    pname = "vim-ddu-source-buffer";
    version = "1238c09bccb1d4814f36d83ef864cbb2b2ca9895";
    src = fetchFromGitHub {
      owner = "shun";
      repo = "ddu-source-buffer";
      rev = "1238c09bccb1d4814f36d83ef864cbb2b2ca9895";
      fetchSubmodules = false;
      sha256 = "sha256-nMFdeFYUGZwAj2ugJ3itOA2ma9mIKq4JbmMr08b/Tcc=";
    };
    date = "2024-04-05";
  };
  vim-ddu-source-dummy = {
    pname = "vim-ddu-source-dummy";
    version = "c7c5c20fa2a7f7e2e228afd51a8b615d06ff491f";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-dummy";
      rev = "c7c5c20fa2a7f7e2e228afd51a8b615d06ff491f";
      fetchSubmodules = false;
      sha256 = "sha256-msnaHsmhQuBShrJ9z7A+5CRKXYfBXZymOQHPfdgScZU=";
    };
    date = "2024-09-03";
  };
  vim-ddu-source-file = {
    pname = "vim-ddu-source-file";
    version = "db0510a1b19d5d9e7d02214884a796914acb495d";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-file";
      rev = "db0510a1b19d5d9e7d02214884a796914acb495d";
      fetchSubmodules = false;
      sha256 = "sha256-74gcMfnUFVjPsKlpPMmt5jyQdqlZRfGyGxnwek0MyNw=";
    };
    date = "2024-09-03";
  };
  vim-ddu-source-file_external = {
    pname = "vim-ddu-source-file_external";
    version = "4866476371886fc3eba73bdf3d3d6fe9ad2efcee";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "ddu-source-file_external";
      rev = "4866476371886fc3eba73bdf3d3d6fe9ad2efcee";
      fetchSubmodules = false;
      sha256 = "sha256-ldutq9hPjjiu1Zw9HeQATDJ4GutaqUv9+7sEbl0nFpI=";
    };
    date = "2024-09-03";
  };
  vim-ddu-source-file_rec = {
    pname = "vim-ddu-source-file_rec";
    version = "3771180decc519a3e09c2c4826740a53997883e1";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-file_rec";
      rev = "3771180decc519a3e09c2c4826740a53997883e1";
      fetchSubmodules = false;
      sha256 = "sha256-IeIjMagARSbjeLgR+u2AfUATPt7xXgyu/iipHt/qHKw=";
    };
    date = "2024-09-03";
  };
  vim-ddu-source-ghq = {
    pname = "vim-ddu-source-ghq";
    version = "2aaba08e41dea7e91043ea2fdc05e65baea7cc6a";
    src = fetchFromGitHub {
      owner = "4513ECHO";
      repo = "ddu-source-ghq";
      rev = "2aaba08e41dea7e91043ea2fdc05e65baea7cc6a";
      fetchSubmodules = false;
      sha256 = "sha256-LYciGeu/EoJw8Nwkil5UGUt4/R7SVtxJPgvVrGnY6hs=";
    };
    date = "2024-09-01";
  };
  vim-ddu-source-git_branch = {
    pname = "vim-ddu-source-git_branch";
    version = "f2b15ea231472a897e6d4e3f3f9fd2b043e9ef6a";
    src = fetchFromGitHub {
      owner = "kyoh86";
      repo = "ddu-source-git_branch";
      rev = "f2b15ea231472a897e6d4e3f3f9fd2b043e9ef6a";
      fetchSubmodules = false;
      sha256 = "sha256-P/OO2fEJZZ/6o8C8O1Rw4V3M6GweMzSnSeMXWWQnCiY=";
    };
    date = "2024-09-08";
  };
  vim-ddu-source-git_diff = {
    pname = "vim-ddu-source-git_diff";
    version = "a0a615adc7f9a90a015a43c6ab25da17d1a57e22";
    src = fetchFromGitHub {
      owner = "kuuote";
      repo = "ddu-source-git_diff";
      rev = "a0a615adc7f9a90a015a43c6ab25da17d1a57e22";
      fetchSubmodules = false;
      sha256 = "sha256-EoBJjkXAMUmEeUHhrCLyYmgouhdzXTZB9pLQ3KRX4VE=";
    };
    date = "2024-08-11";
  };
  vim-ddu-source-git_diff_tree = {
    pname = "vim-ddu-source-git_diff_tree";
    version = "95eed224bcea44c57cfa8ac500fbc8dcab2831a0";
    src = fetchFromGitHub {
      owner = "kyoh86";
      repo = "ddu-source-git_diff_tree";
      rev = "95eed224bcea44c57cfa8ac500fbc8dcab2831a0";
      fetchSubmodules = false;
      sha256 = "sha256-A8ixfPvGMJSNHYfhu6Ya/rt4L3VmIhFuV/5pJXtzdUw=";
    };
    date = "2024-09-08";
  };
  vim-ddu-source-git_log = {
    pname = "vim-ddu-source-git_log";
    version = "8539b653b10246f1bec721a632e880ceb1cc2eda";
    src = fetchFromGitHub {
      owner = "kyoh86";
      repo = "ddu-source-git_log";
      rev = "8539b653b10246f1bec721a632e880ceb1cc2eda";
      fetchSubmodules = false;
      sha256 = "sha256-3Ve8uiqJva45Oxi7M4JAkywlDzWEcxjTrPGFN8mktO8=";
    };
    date = "2024-09-08";
  };
  vim-ddu-source-git_status = {
    pname = "vim-ddu-source-git_status";
    version = "31d4aabb2e6f54a0f4278751283c45245896e522";
    src = fetchFromGitHub {
      owner = "kuuote";
      repo = "ddu-source-git_status";
      rev = "31d4aabb2e6f54a0f4278751283c45245896e522";
      fetchSubmodules = false;
      sha256 = "sha256-j1c7yYpbtZdEEWjasC4hZSBAOGk7/EZJqvX5mSYFklE=";
    };
    date = "2024-08-11";
  };
  vim-ddu-source-help = {
    pname = "vim-ddu-source-help";
    version = "b25d3b89b5e70c7d6b1bbc29d8db66fcbe2b00e4";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "ddu-source-help";
      rev = "b25d3b89b5e70c7d6b1bbc29d8db66fcbe2b00e4";
      fetchSubmodules = false;
      sha256 = "sha256-aUMZ30dib5irpK6sY5MX+3vnXGSSbU2iHFLvPlktkEo=";
    };
    date = "2023-11-18";
  };
  vim-ddu-source-highlight = {
    pname = "vim-ddu-source-highlight";
    version = "4b6656ef3043de6a7d87d5637ceb8cf8e2c85d99";
    src = fetchFromGitHub {
      owner = "matsui54";
      repo = "ddu-source-highlight";
      rev = "4b6656ef3043de6a7d87d5637ceb8cf8e2c85d99";
      fetchSubmodules = false;
      sha256 = "sha256-hhYIF4YhUSu/O0OcIvhbiaSwepvw/PYO68NKMm1grBg=";
    };
    date = "2023-05-16";
  };
  vim-ddu-source-line = {
    pname = "vim-ddu-source-line";
    version = "32e88d2e335c8b4346906c03eaca8480bf22fe64";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-line";
      rev = "32e88d2e335c8b4346906c03eaca8480bf22fe64";
      fetchSubmodules = false;
      sha256 = "sha256-iKur1PPR99SnZgvy0/aZ+O+1tCX69nGA5Aro62oRG8g=";
    };
    date = "2024-09-03";
  };
  vim-ddu-source-lsp = {
    pname = "vim-ddu-source-lsp";
    version = "b9df7182658ca7955cc20416d86efc935e685e7d";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "ddu-source-lsp";
      rev = "b9df7182658ca7955cc20416d86efc935e685e7d";
      fetchSubmodules = false;
      sha256 = "sha256-sUSLr5HuoI2ZcAz2Vl5mDVsTHzm92pk1GON6Jj4nR2I=";
    };
    date = "2024-05-19";
  };
  vim-ddu-source-mr = {
    pname = "vim-ddu-source-mr";
    version = "88434598c654e4bd3e1454bbccc7b99f1023c2db";
    src = fetchFromGitHub {
      owner = "kuuote";
      repo = "ddu-source-mr";
      rev = "88434598c654e4bd3e1454bbccc7b99f1023c2db";
      fetchSubmodules = false;
      sha256 = "sha256-FJa/bHfFpg81xKlbrn50NCaROnwuWJGrpQN12Lmi47o=";
    };
    date = "2024-09-01";
  };
  vim-ddu-source-nvim-notify = {
    pname = "vim-ddu-source-nvim-notify";
    version = "722175b49a319f51dffbacc180b023ae37385a6e";
    src = fetchFromGitHub {
      owner = "yuki-yano";
      repo = "ddu-source-nvim-notify";
      rev = "722175b49a319f51dffbacc180b023ae37385a6e";
      fetchSubmodules = false;
      sha256 = "sha256-RfX2F9/0jo1mtf5J/3LhOiNGl4Xe6fjRLhVv1r9i0Co=";
    };
    date = "2023-08-07";
  };
  vim-ddu-source-path_history = {
    pname = "vim-ddu-source-path_history";
    version = "10e9442e9265d5e005ef041f5ed936dca031c6ab";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-path_history";
      rev = "10e9442e9265d5e005ef041f5ed936dca031c6ab";
      fetchSubmodules = false;
      sha256 = "sha256-9CfrJVLiD5EKRYpBYYL/JRndFuU9WYwsUY98A2nDOYE=";
    };
    date = "2024-09-03";
  };
  vim-ddu-source-register = {
    pname = "vim-ddu-source-register";
    version = "94c71a4193ff30d7d80b6076fb39b94f5cf10fe3";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-source-register";
      rev = "94c71a4193ff30d7d80b6076fb39b94f5cf10fe3";
      fetchSubmodules = false;
      sha256 = "sha256-jCQDoV6EncXp4yQcBVfrgVSdwsBxt1b3dZUUTASQqnE=";
    };
    date = "2024-09-03";
  };
  vim-ddu-source-rg = {
    pname = "vim-ddu-source-rg";
    version = "4e856b8ae2fc67b4e43c7c085577835ea1ac395f";
    src = fetchFromGitHub {
      owner = "shun";
      repo = "ddu-source-rg";
      rev = "4e856b8ae2fc67b4e43c7c085577835ea1ac395f";
      fetchSubmodules = false;
      sha256 = "sha256-/xj59knsaaWj77WPwCnN/bWTIMww+5MH/t8sPQrI6FI=";
    };
    date = "2024-09-03";
  };
  vim-ddu-ui-ff = {
    pname = "vim-ddu-ui-ff";
    version = "ebab43049da919b6bdba89cc345bea7ba4fe102b";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-ui-ff";
      rev = "ebab43049da919b6bdba89cc345bea7ba4fe102b";
      fetchSubmodules = false;
      sha256 = "sha256-IHKAs7Kc/51Mi80vkPll1kZiIilV5yWzxcN2A82E9bw=";
    };
    date = "2024-10-03";
  };
  vim-ddu-ui-filer = {
    pname = "vim-ddu-ui-filer";
    version = "6a019b2b0fcdcc79dca90807ed24dc899b7e5d13";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "ddu-ui-filer";
      rev = "6a019b2b0fcdcc79dca90807ed24dc899b7e5d13";
      fetchSubmodules = false;
      sha256 = "sha256-Fkb0Q/8QqvBTRCESL+FgMiMhXTCwr2rp2iDaY8yIcWU=";
    };
    date = "2024-10-03";
  };
  vim-denippet = {
    pname = "vim-denippet";
    version = "9a19bb6ddcdeb7a60860ac27e180d6d400ab10c7";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "denippet.vim";
      rev = "9a19bb6ddcdeb7a60860ac27e180d6d400ab10c7";
      fetchSubmodules = false;
      sha256 = "sha256-98EGTcsh6wRkAcYKUBj2ar6HkCZav6wAt54xYrS/pJY=";
    };
    date = "2024-06-27";
  };
  vim-denippet-autoimport-vscode = {
    pname = "vim-denippet-autoimport-vscode";
    version = "81c09c53a61e4b42234fee43ce26f0ceb196b9b7";
    src = fetchFromGitHub {
      owner = "ryoppippi";
      repo = "denippet-autoimport-vscode";
      rev = "81c09c53a61e4b42234fee43ce26f0ceb196b9b7";
      fetchSubmodules = false;
      sha256 = "sha256-g3W4Ski+8dkY9fMfnFpi2Irytou4qSqb6Gess7LN7aI=";
    };
    date = "2024-05-06";
  };
  vim-friendly-snippets = {
    pname = "vim-friendly-snippets";
    version = "de8fce94985873666bd9712ea3e49ee17aadb1ed";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "de8fce94985873666bd9712ea3e49ee17aadb1ed";
      fetchSubmodules = false;
      sha256 = "sha256-H94Ryad0ZsSg/gioUgW+7sowij7GgtEUMNFi1IOZAys=";
    };
    date = "2024-10-07";
  };
  vim-neco = {
    pname = "vim-neco";
    version = "1b95bedbeed0b4c81466d40b16bfb0c0ff16721d";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "neco-vim";
      rev = "1b95bedbeed0b4c81466d40b16bfb0c0ff16721d";
      fetchSubmodules = false;
      sha256 = "sha256-5tFAsxc7qYOw611qCsMc8iDjpydlm7s3ZSPir7zfNz8=";
    };
    date = "2023-08-15";
  };
  vim-pum = {
    pname = "vim-pum";
    version = "b2ca20dedf32b80dd0cbd654770ec3f70841be68";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "pum.vim";
      rev = "b2ca20dedf32b80dd0cbd654770ec3f70841be68";
      fetchSubmodules = false;
      sha256 = "sha256-wY0El/2VHJ9aTls0bS+T6iuZKfCMDnRJqoT6kYOCAOM=";
    };
    date = "2024-10-09";
  };
  vim-readme-viewer = {
    pname = "vim-readme-viewer";
    version = "f13692cabde3129f35758b94d5798f5c9c1ab49a";
    src = fetchFromGitHub {
      owner = "4513ECHO";
      repo = "vim-readme-viewer";
      rev = "f13692cabde3129f35758b94d5798f5c9c1ab49a";
      fetchSubmodules = false;
      sha256 = "sha256-n7O25ZpsgbEdGC4skrsHOJmtvIzOBRe58hLyKONOU20=";
    };
    date = "2024-01-04";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "0b3adf1b39a9ccc4e0ee99b77a5a08de0130f555";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "0b3adf1b39a9ccc4e0ee99b77a5a08de0130f555";
      fetchSubmodules = false;
      sha256 = "sha256-7Vb/9qik/Oep5CvlVwVesXtGxu+hy2VpWtoCiRSXmO8=";
    };
    date = "2024-10-13";
  };
}
