#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Color #####

WHITE=0xffffffff
BAR_COLOR=1xff140c42
BAR_COLOR=0x12181825
ITEM_BG_COLOR=1xff2b1c84
ACCENT_COLOR=1xffeb46f9

############## BAR ##############

sketchybar --bar height=45 \
                 y_offset=0 \
                 blur_radius=0 \
                 position=top \
                 padding_left=4 \
                 padding_right=4 \
                 margin=0 \
                 corner_radius=0 \
                 color=0xff1e1d2e \
                 shadow=on

############## GLOBAL DEFAULTS ##############

sketchybar --default updates=when_shown \
                     icon.font="Hack Nerd Font:Bold:12.0" \
                     icon.color=0xffECEFF4 \
                     icon.highlight_color=0xffE48FA8 \
                     label.font="Hack Nerd Font:Bold:12.0" \
                     label.color=0xffECEFF4 \
                     background.corner_radius=5 \
                     background.height=20

sketchybar --add item logo left \
           --set logo icon= \
                 icon.color=0xff010101 \
                 icon.padding_left=16 \
                 icon.padding_right=16 \
                 background.color=0xffA5E0D5 \
                 background.padding_right=8 \
                 background.padding_left=4 \
                 click_script="sketchybar --update"

sketchybar --add item space_separator left \
           --set space_separator icon= \
                                 background.padding_left=23 \
                                 background.padding_right=23 \
                                 label.drawing=off \
                                 icon.color=0xff92B3F5

sketchybar --add item window_title left \
           --set window_title script="$PLUGIN_DIR/window_title.sh" \
                              icon.drawing=off \
                              label.color=0xffb7bdf4 \
           --subscribe window_title front_app_switched

############## ITEM DEFAULTS ###############

sketchybar --default label.padding_left=6 \
                     label.padding_right=6 \
                     icon.padding_left=6 \
                     icon.padding_right=6 \
                     icon.font="Hack Nerd Font:Bold:20.0" \
                     background.height=30 \
                     background.padding_right=4 \
                     background.padding_left=4 \
                     background.corner_radius=5

############## RIGHT ITEMS ##############

sketchybar --add item time right \
           --set time update_freq=1 \
                      icon.drawing=off \
                      script="$PLUGIN_DIR/time.sh" \
                      background.color=0xff3C3E4F \
                      background.padding_left=0

sketchybar --add item time_logo right\
           --set time_logo icon= \
                           label.drawing=off \
                           icon.color=0xff121219 \
                           label.drawing=off \
                           background.color=0xffF5E3B5

sketchybar --add item date right \
           --set date update_freq=1000 \
                      icon.drawing=off \
                      script="$PLUGIN_DIR/date.sh" \
                      background.color=0xff3C3E4F \
                      background.padding_left=0

sketchybar --add item clock_logo right\
           --set clock_logo icon= \
                            icon.color=0xff121219\
                            label.drawing=off \
                            background.color=0xff92B3F5

sketchybar --add item battery right \
           --set battery update_freq=3 \
                         icon.drawing=off \
                         script="$PLUGIN_DIR/power.sh" \
                         background.color=0xff3C3E4F \
                         background.padding_left=0

sketchybar --add item power_logo right \
           --set power_logo icon= \
                            icon.color=0xff121219 \
                            label.drawing=off \
                            background.color=0xffB3E1A7

############## UPDATE ##############

sketchybar --update
