name: Run setup-nix
description: Set up Nix environment for GitHub Actions

inputs:
  cachix-auth-token:
    required: true

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v14
      with:
        name: nixos-configuration
        authToken: '${{ inputs.cachix-auth-token }}'
